/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void knob1_turn1(GKnob source, GEvent event) { //_CODE_:modeknob:727750:
  setModeKnob(source);
} //_CODE_:modeknob:727750:

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:logo:704728:
} //_CODE_:logo:704728:

public void wavButton_click1(GImageButton source, GEvent event) { //_CODE_:wavButton:649965:
  openWavMenu();
} //_CODE_:wavButton:649965:

public void envButton_click1(GImageButton source, GEvent event) { //_CODE_:envButton:585026:
  openEnvMenu();
} //_CODE_:envButton:585026:

public void imgButton_click1(GImageButton source, GEvent event) { //_CODE_:imgButton:805293:
  openImgMenu();
} //_CODE_:imgButton:805293:

public void ModeText_click1(GImageButton source, GEvent event) { //_CODE_:ModeText:750609:
} //_CODE_:ModeText:750609:

public void VolText_click1(GImageButton source, GEvent event) { //_CODE_:VolText:249241:
  //println("imgButton6 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:VolText:249241:

public void KnobNums_click1(GImageButton source, GEvent event) { //_CODE_:KnobNums:641804:
  //println("imgButton7 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:KnobNums:641804:

public void knob2_turn1(GKnob source, GEvent event) { //_CODE_:volknob:873452:
  setVolKnob(source);
} //_CODE_:volknob:873452:

public void greenCon_click1(GImageButton source, GEvent event) { //_CODE_:greenCon:794411:
  //println("imgButton8 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:greenCon:794411:

public void redCon_click1(GImageButton source, GEvent event) { //_CODE_:redCon:582663:
  //println("imgButton9 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:redCon:582663:

public void helpButton_click1(GImageButton source, GEvent event) { //_CODE_:helpButton:816277:
  openHelpMenu();
} //_CODE_:helpButton:816277:


// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.GOLD_SCHEME);
  G4P.setMouseOverEnabled(false);
  G4P.setDisplayFont("SignPainter", G4P.BOLD, 18);
  G4P.setSliderFont("SignPainter", G4P.BOLD, 15);
  surface.setTitle("Smpl-A-Sketch");
  modeknob = new GKnob(this, 72, 360, 72, 72, 0.8);
  modeknob.setTurnRange(160, 20);
  modeknob.setTurnMode(GKnob.CTRL_HORIZONTAL);
  modeknob.setSensitivity(1);
  modeknob.setShowArcOnly(false);
  modeknob.setOverArcOnly(false);
  modeknob.setIncludeOverBezel(false);
  modeknob.setShowTrack(true);
  modeknob.setLimits(0.0, 0.0, 2.0);
  modeknob.setNbrTicks(3);
  modeknob.setStickToTicks(true);
  modeknob.setShowTicks(true);
  modeknob.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  modeknob.setOpaque(false);
  modeknob.addEventHandler(this, "knob1_turn1");
  displaylabel = new GLabel(this, 36, 24, 640, 320);
  displaylabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  displaylabel.setLocalColorScheme(GCScheme.SCHEME_8);
  displaylabel.setOpaque(false);
  logo = new GImageButton(this, 224, 364, new String[] { "BigLogo.png", "BigLogo.png", "BigLogo.png" } );
  logo.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  logo.addEventHandler(this, "imgButton1_click1");
  wavButton = new GImageButton(this, 48, 396, 19, 15, new String[] { "wavBg.png", "wavBg.png", "wavBg.png" } );
  wavButton.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  wavButton.addEventHandler(this, "wavButton_click1");
  envButton = new GImageButton(this, 96, 348, 25, 10, new String[] { "envBg.png", "envBg.png", "envBg.png" } );
  envButton.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  envButton.addEventHandler(this, "envButton_click1");
  imgButton = new GImageButton(this, 150, 396, 19, 16, new String[] { "camBg.png", "camBg.png", "camBg.png" } );
  imgButton.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  imgButton.addEventHandler(this, "imgButton_click1");
  ModeText = new GImageButton(this, 84, 433, new String[] { "mode.png", "mode.png", "mode.png" } );
  ModeText.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  ModeText.addEventHandler(this, "ModeText_click1");
  VolText = new GImageButton(this, 588, 433, new String[] { "vol.png", "vol.png", "vol.png" } );
  VolText.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  VolText.addEventHandler(this, "VolText_click1");
  KnobNums = new GImageButton(this, 556, 350, new String[] { "VolKnob.png", "VolKnob.png", "VolKnob.png" } );
  KnobNums.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  KnobNums.addEventHandler(this, "KnobNums_click1");
  volknob = new GKnob(this, 564, 360, 72, 72, 0.8);
  volknob.setTurnRange(110, 70);
  volknob.setTurnMode(GKnob.CTRL_HORIZONTAL);
  volknob.setSensitivity(1);
  volknob.setShowArcOnly(false);
  volknob.setOverArcOnly(false);
  volknob.setIncludeOverBezel(false);
  volknob.setShowTrack(true);
  volknob.setLimits(2.0, 0.0, 10.0);
  volknob.setNbrTicks(11);
  volknob.setStickToTicks(true);
  volknob.setShowTicks(true);
  volknob.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  volknob.setOpaque(false);
  volknob.addEventHandler(this, "knob2_turn1");
  greenCon = new GImageButton(this, 689, 5, new String[] { "congreen.png", "congreen.png", "congreen.png" } );
  greenCon.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  greenCon.addEventHandler(this, "greenCon_click1");
  redCon = new GImageButton(this, 689, 5, new String[] { "conred.png", "conred.png", "conred.png" } );
  redCon.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  redCon.addEventHandler(this, "redCon_click1");
  helpButton = new GImageButton(this, 11, 5, new String[] { "help.png", "help.png", "help.png" } );
  helpButton.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  helpButton.addEventHandler(this, "helpButton_click1");
}

// Variable declarations 
// autogenerated do not edit
GKnob modeknob; 
GLabel displaylabel; 
GImageButton logo; 
GImageButton wavButton; 
GImageButton envButton; 
GImageButton imgButton; 
GImageButton ModeText; 
GImageButton VolText; 
GImageButton KnobNums; 
GKnob volknob; 
GImageButton greenCon; 
GImageButton redCon; 
GImageButton helpButton; 
