/* autogenerated by Processing revision 1307 on 2025-10-12 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.Map;
import processing.sound.*;
import g4p_controls.*;
import processing.video.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class smplasketch extends PApplet {





Sound s;

boolean test = false;

//Camera Dimensions Setup
int[] sizeArr = {640, 480}; //fix width to match pi cam(mac cam is 640 480)
int camwidth = sizeArr[0];
int camheight = sizeArr[1];

public void setup() {
  //GUI Setup
  /* size commented out by preprocessor */;
  createGUI();
  //Img processing setup
  modWavImg = createImage(camwidth, camheight, RGB); // Create image to write other data to
  modEnvImg = createImage(camwidth, camheight, RGB); // Create env image to write other data to
  initImgFromFile("test.png");
  searchForCamera();
  //clear cache
  clearCache();
  //Setup volume control
  s = new Sound(this);
  s.volume(0.2f);
  //
}

public void draw() {
  background(143, 3, 3);
  checkMode();
  checkForConnection();
}

public void keyPressed() { //test true is for keyboard control test false is obscure ascii to talk to teensy
  if ((test == true && key == 'w')||(test == false && key == '€')) {
    wavSnap();
    println("wavSnap");
  } else if ((test == true && key == 'e')||(test == false && key == 'ƒ')) {
    envSnap();
    println("envSnap");
  } else if ((test == true && key == '[')||(test == false && key == '†')) {
    decEnvMult();
    println("decEnv");
  } else if ((test == true && key == ']')||(test == false && key == '‡')) {
    incEnvMult();
    println("incEnv");
  } else if ((test == true && key == '-')||(test == false && key == '‰')) {
    decWavMult();
    println("decWav");
  } else if ((test == true && key == '=')||(test == false && key == '°')) {
    incWavMult();
    println("incWav");
  } else if ((test == true && key == 's')||(test == false && key == 'Œ')) {
    smpl();
    println("smpl");
  } else if ((test == true && key == 'r')||(test == false && key == '™')) {
    resetWav();
    println("resetWav");
  } else if ((test == true && key == 't')||(test == false && key == '◊')) {
    resetEnv();
    println("resetEnv");
  } else if (key == (char)27) {//Escape key always exits program
    clearCache();
    println("Program Exit");
    exit();
  } else if (key == (char)32) {
    clearActiveSamples();
  }
}
float volume = 0.2f;
float wavMult = 1;
float envMult = 1;

//Waveform Generation
public AudioSample createSample(float[] wav) { //create sample object from float array
  AudioSample sample = new AudioSample(this, wav, 200 * camwidth);
  return sample;
}

public void playWav(AudioSample sample) { //takes in sample object and plays it
  sample.rate(0.7f * wavMult); //add pitch shift due to button input
  sample.loop();
}

public void playWav(AudioSample sample, float rate) { //takes in sample object and plays it
  sample.rate(rate); //add pitch shift due to button input
  sample.loop();
}


// Envelope Generation
public float[] getTimeVals() { //translate envImage processing code into values needed to play the envelope back
  float[] timeVals = new float[3];
  float[] splits = processEnvImage();
  timeVals[0] = (splits[0]/100) * 0.45f;
  timeVals[1] = ((splits[1]-splits[0])/100) * 0.45f;
  timeVals[2] = ((100-splits[1])/100) * 0.45f;
  return timeVals;
}

public void playEnv(AudioSample sample) { //takes in a sample object and using the variables plays an envelope
  Env env = new Env(this);
  float[] time = getTimeVals();
  float attackTime = time[0];
  float sustainTime = time[1];
  float releaseTime = time[2];
  env.play(sample, attackTime * envMult, sustainTime * envMult, 1.0f, releaseTime);
}

public void playDemoEnv(AudioSample sample) { //takes in a demo object and using the variables plays a demo envelope
  Env env = new Env(this);
  float[] time = resetEnv;
  float attackTime = time[0];
  float sustainTime = time[1];
  float releaseTime = time[2];
  env.play(sample, attackTime * envMult, sustainTime * envMult, 1.0f, releaseTime);
}

public void playSliderEnv(AudioSample sample) { //takes in a demo object and using the variables plays a demo envelope
  Env env = new Env(this);
  int[] time = sliderVals;
  float attackTime = map(time[0], 0, 10, 0.f, 1.f);
  float sustainTime = map(time[1], 0, 10, 0.f, 1.f);
  float releaseTime = map(time[2], 0, 10, 0.f, 1.f);
  env.play(sample, attackTime * envMult, sustainTime * envMult, 1.0f, releaseTime);
}
boolean clearWav = true;
boolean wavControl = true;
boolean clearEnv = true;
boolean susMode = false;
boolean sliderMode = false;
int[] sliderVals = new int[3];
boolean spaceHit = false;
ArrayList<AudioSample> endSus = new ArrayList<AudioSample>();

public void checkForConnection() { 
  if (key == '±') {
    drawConnectionIcon(true);
  } else if (key == 'o') {
    //drawConnectionIcon(false);
  }
}

public void wavSnap() {
  takePicture("wav_image");
  wavImg = loadImage("wav_image.jpg");
  clearWav = false;
}

public void envSnap() {
  takePicture("env_image");
  envImg = loadImage("env_image.jpg");
  clearEnv = false;
}

public void incWavMult() {
  if (wavMult < 2.0f) {
    wavMult += 0.1f;
  }
}

public void decWavMult() {
  if (wavMult > 0.5f) {
    wavMult -= 0.1f;
  }
}

public void incEnvMult() {
  if (envMult < 2.0f) {
    envMult += 0.1f;
  }
}

public void decEnvMult() {
  if (envMult > 0.5f) {
    envMult -= 0.1f;
  }
}

public void resetWav() {
  wavMult=1;
  clearWav = true;
  filereset.save("wav_image.jpg");
}

public void resetEnv() {
  envMult =1;
  clearEnv = true;
  susMode = false;
  sliderMode = false;
  filereset.save("env_image.jpg");
}

public void smpl() {
  if (mode != 2.0f) {
    float[] wav;
    if (clearWav && wavControl) {
      wav = resetSin;
    } else if (!wavControl) {
      wav = defaultWav;
    } else {
      wav = processWavImage();
    }
    AudioSample smpl = createSample(wav);
    playWav(smpl);
    if (clearEnv) {
      playDemoEnv(smpl);
    } else if (susMode) {
      endSus.add(smpl);
    } else if (sliderMode) {
      playSliderEnv(smpl);
    } else {
      playEnv(smpl);
    }
  } else {
    photowaveformSmpl();
  }
}

public void photowaveformSmpl() { //this is very rudimentary and will do more later
  ArrayList<float[]> processed = processMultiImage(imageMode);
  float[] wavR = processed.get(0);
  float[] wavG = processed.get(1);
  float[] wavB = processed.get(2);
  AudioSample smplR = createSample(wavR);
  AudioSample smplG = createSample(wavG);
  AudioSample smplB = createSample(wavB);
  AudioSample body = createSample(resetSin);
  playWav(body, 0.75f*wavMult);
  playWav(smplR, 1.0f*wavMult);
  playWav(smplG, 1.5f*wavMult);
  playWav(smplB, 2.0f*wavMult);
  if (clearEnv) {
    playDemoEnv(body);
    playDemoEnv(smplR);
    playDemoEnv(smplG);
    playDemoEnv(smplB);
  } else if (susMode) {
    endSus.add(body);
    endSus.add(smplR);
    endSus.add(smplG);
    endSus.add(smplB);
  } else if (sliderMode) {
    playSliderEnv(body);
    playSliderEnv(smplR);
    playSliderEnv(smplG);
    playSliderEnv(smplB);
  } else {
    playEnv(body);
    playEnv(smplR);
    playEnv(smplG);
    playEnv(smplB);
  }
}


Capture cam;


public void searchForCamera() {
  String[] cameras = Capture.list();

  if (cameras.length == 0) {
    println("There are no cameras available for capture.");
    exit();
  } else {
    println("Available cameras:");
    int setcamIndex = -1;
    for (int i = 0; i < cameras.length; i++) {
      println(cameras[i]);
      if (cameras[i].contains("C270")) {
        setcamIndex = i;
      }
    }
    if (setcamIndex != -1 || test) {//allows the program to run eve when device is not connected while testing
      if (test) {
        cam = new Capture(this, 850, 900, "pipeline:avfvideosrc device-index=0", 30);
      } else {
        cam = new Capture(this, 850, 900, "pipeline:avfvideosrc device-index="+setcamIndex, 30);
      }
      cam.start();
    } else {
      //display no camera connected dialouge
      wait(5000);
      exit();
    }
  }
}

public void takePicture(String imageName) {
  //delay(1000);
  if (cam.available() == true) {
    cam.read();
  }
  cam.save(imageName+".jpg");
  //image(cam, 0, 0);
}
float[] resetSin = genSinWav();
float[] resetEnv = genBasicEnv();
float mode = 0.0f; //0.0 is Wav Mode 1.0 is Env Mode 2.0 is IMG mode
float prevMode = 0.0f;

public void wavMode(float[] wav) { //Draw Screen, draw wav, draw outline
  drawScreen();
  drawWav(wav);
  drawScreenBox();
}

public void envMode(float[] env) {//Draw Screen, draw env, draw outline
  drawScreen();
  drawEnv(env);
  drawScreenBox();
}
public void imgMode() { //Draw Screen, draw wavs(need to add), draw outline
  drawScreen();
  ArrayList<float[]> arrList = processMultiImage(imageMode);
  int counter = 0;
  for (float[] f : arrList) {
    if (counter == 0) {
      drawWav(f, 255, 0, 0);
    } else if (counter == 1) {
      drawWav(f, 0, 255, 0);
    } else if (counter == 2) {
      drawWav(f, 0, 0, 255);
    }
    counter++;
  }
  drawScreenBox();
}

public void checkMode() { //Would do else ifs but this logic makes the knob smoother
  if (0.0f == mode || prevMode == 0.0f) {
    if (clearWav && wavControl) {
      wavMode(resetSin);
    } else if(!wavControl) {
    wavMode(defaultWav);
    }else {
      wavMode(processWavImage());
    }
    prevMode = 0.0f;
  }
  if (1.0f == mode || prevMode == 1.0f) {
    if (clearEnv) {
      envMode(resetEnv);
    } else if (susMode) {
      envMode(new float[]{0.1f, 0.9f, 0});
    } else if (sliderMode) {
      float[] mappedSliders = new float[]{map(sliderVals[0], 0, 10, 0.f, 1.f), map(sliderVals[1], 0, 10, 0.f, 1.f), map(sliderVals[2], 0, 10, 0.f, 1.f)};
      envMode(mappedSliders);
    } else {
      envMode(getTimeVals());
    }
    prevMode = 1.0f;
  }
  if (2.0f == mode || prevMode ==2.0f) {
    imgMode();
    prevMode = 2.0f;
  }
}
//Data Mapping
public float[] mappedFlArr(float[] flArr) { //Map wav values to fit the ui screen
  float[] temp = new float[flArr.length];
  for (int i = 0; i < flArr.length; i++) {
    temp[i] = map(flArr[i], -1, 1, 40, 320);
  }
  return temp;
}

public float[] mapEnv(float[] env) { //Map envelope values to fit the ui screen
  float totalTime = env[0]+env[1]+env[2];
  float attackTime = map(env[0], 0.0f, totalTime, 0, 640);
  float sustainTime = map(env[1], 0.0f, totalTime, 0, 640);
  float releaseTime = map(env[2], 0.0f, totalTime, 0, 640);
  return new float[]{attackTime, sustainTime, releaseTime};
}

//Draw Functions
public void drawScreen() { //draw blank screen
  fill(255);
  stroke(0);
  strokeWeight(2);
  rect(40, 20, 640, 320);
}

public void drawScreenBox() {//draw screen outline
  stroke(0);
  strokeWeight(2);
  noFill();
  rect(40, 20, 640, 320);
}


public void drawWav(float[] wavArr) { //takes wav arr draws it
  stroke(225, 0, 0);
  strokeWeight(2);
  float[] wav = mappedFlArr(wavArr);
  for (int i = 0; i < wav.length-1; i ++) {
    line(i+40, wav[i], i+41, wav[i+1]);
  }
}

public void drawWav(float[] wavArr, int r, int g, int b) { //takes wav arr draws it
  stroke(r, g, b);
  strokeWeight(2);
  float[] wav = mappedFlArr(wavArr);
  for (int i = 0; i < wav.length-1; i ++) {
    line(i+40, wav[i], i+41, wav[i+1]);
  }
}

public void drawEnv(float[] envArr) { //takes env arr draws it
  stroke(225, 0, 0);
  strokeWeight(2);
  float[] env = mapEnv(envArr);
  line(40, 340, 40+env[0], 200);
  line(40+env[0], 200, 40+env[0]+env[1], 200);
  line(40+env[0]+env[1], 200, 680, 340);
}

public void drawConnectionIcon(boolean bool) { //true for on false for off
  redCon.setVisible(!bool);
}
/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void knob1_turn1(GKnob source, GEvent event) { //_CODE_:modeknob:727750:
  setModeKnob(source);
} //_CODE_:modeknob:727750:

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:logo:704728:
} //_CODE_:logo:704728:

public void wavButton_click1(GImageButton source, GEvent event) { //_CODE_:wavButton:649965:
  openWavMenu();
} //_CODE_:wavButton:649965:

public void envButton_click1(GImageButton source, GEvent event) { //_CODE_:envButton:585026:
  openEnvMenu();
} //_CODE_:envButton:585026:

public void imgButton_click1(GImageButton source, GEvent event) { //_CODE_:imgButton:805293:
} //_CODE_:imgButton:805293:

public void ModeText_click1(GImageButton source, GEvent event) { //_CODE_:ModeText:750609:
} //_CODE_:ModeText:750609:

public void VolText_click1(GImageButton source, GEvent event) { //_CODE_:VolText:249241:
  //println("imgButton6 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:VolText:249241:

public void KnobNums_click1(GImageButton source, GEvent event) { //_CODE_:KnobNums:641804:
  //println("imgButton7 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:KnobNums:641804:

public void knob2_turn1(GKnob source, GEvent event) { //_CODE_:volknob:873452:
  setVolKnob(source);
} //_CODE_:volknob:873452:

public void greenCon_click1(GImageButton source, GEvent event) { //_CODE_:greenCon:794411:
  //println("imgButton8 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:greenCon:794411:

public void redCon_click1(GImageButton source, GEvent event) { //_CODE_:redCon:582663:
  //println("imgButton9 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:redCon:582663:

public void helpButton_click1(GImageButton source, GEvent event) { //_CODE_:helpButton:816277:
  openHelpMenu();
} //_CODE_:helpButton:816277:


// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.GOLD_SCHEME);
  G4P.setMouseOverEnabled(false);
  G4P.setDisplayFont("SignPainter", G4P.BOLD, 18);
  G4P.setSliderFont("SignPainter", G4P.BOLD, 15);
  surface.setTitle("Smpl-A-Sketch");
  modeknob = new GKnob(this, 72, 360, 72, 72, 0.8f);
  modeknob.setTurnRange(160, 20);
  modeknob.setTurnMode(GKnob.CTRL_HORIZONTAL);
  modeknob.setSensitivity(1);
  modeknob.setShowArcOnly(false);
  modeknob.setOverArcOnly(false);
  modeknob.setIncludeOverBezel(false);
  modeknob.setShowTrack(true);
  modeknob.setLimits(0.0f, 0.0f, 2.0f);
  modeknob.setNbrTicks(3);
  modeknob.setStickToTicks(true);
  modeknob.setShowTicks(true);
  modeknob.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  modeknob.setOpaque(false);
  modeknob.addEventHandler(this, "knob1_turn1");
  displaylabel = new GLabel(this, 36, 24, 640, 320);
  displaylabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  displaylabel.setLocalColorScheme(GCScheme.SCHEME_8);
  displaylabel.setOpaque(false);
  logo = new GImageButton(this, 224, 364, new String[] { "BigLogo.png", "BigLogo.png", "BigLogo.png" } );
  logo.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  logo.addEventHandler(this, "imgButton1_click1");
  wavButton = new GImageButton(this, 48, 396, 19, 15, new String[] { "wavBg.png", "wavBg.png", "wavBg.png" } );
  wavButton.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  wavButton.addEventHandler(this, "wavButton_click1");
  envButton = new GImageButton(this, 96, 348, 25, 10, new String[] { "envBg.png", "envBg.png", "envBg.png" } );
  envButton.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  envButton.addEventHandler(this, "envButton_click1");
  imgButton = new GImageButton(this, 150, 396, 19, 16, new String[] { "camBg.png", "camBg.png", "camBg.png" } );
  imgButton.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  imgButton.addEventHandler(this, "imgButton_click1");
  ModeText = new GImageButton(this, 84, 433, new String[] { "mode.png", "mode.png", "mode.png" } );
  ModeText.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  ModeText.addEventHandler(this, "ModeText_click1");
  VolText = new GImageButton(this, 588, 433, new String[] { "vol.png", "vol.png", "vol.png" } );
  VolText.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  VolText.addEventHandler(this, "VolText_click1");
  KnobNums = new GImageButton(this, 556, 350, new String[] { "VolKnob.png", "VolKnob.png", "VolKnob.png" } );
  KnobNums.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  KnobNums.addEventHandler(this, "KnobNums_click1");
  volknob = new GKnob(this, 564, 360, 72, 72, 0.8f);
  volknob.setTurnRange(110, 70);
  volknob.setTurnMode(GKnob.CTRL_HORIZONTAL);
  volknob.setSensitivity(1);
  volknob.setShowArcOnly(false);
  volknob.setOverArcOnly(false);
  volknob.setIncludeOverBezel(false);
  volknob.setShowTrack(true);
  volknob.setLimits(2.0f, 0.0f, 10.0f);
  volknob.setNbrTicks(11);
  volknob.setStickToTicks(true);
  volknob.setShowTicks(true);
  volknob.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  volknob.setOpaque(false);
  volknob.addEventHandler(this, "knob2_turn1");
  greenCon = new GImageButton(this, 689, 5, new String[] { "congreen.png", "congreen.png", "congreen.png" } );
  greenCon.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  greenCon.addEventHandler(this, "greenCon_click1");
  redCon = new GImageButton(this, 689, 5, new String[] { "conred.png", "conred.png", "conred.png" } );
  redCon.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  redCon.addEventHandler(this, "redCon_click1");
  helpButton = new GImageButton(this, 11, 5, new String[] { "help.png", "help.png", "help.png" } );
  helpButton.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  helpButton.addEventHandler(this, "helpButton_click1");
}

// Variable declarations 
// autogenerated do not edit
GKnob modeknob; 
GLabel displaylabel; 
GImageButton logo; 
GImageButton wavButton; 
GImageButton envButton; 
GImageButton imgButton; 
GImageButton ModeText; 
GImageButton VolText; 
GImageButton KnobNums; 
GKnob volknob; 
GImageButton greenCon; 
GImageButton redCon; 
GImageButton helpButton; 
PImage wavImg; //<>//
PImage envImg;
PImage modWavImg;
PImage modEnvImg;

public int findAvgY(ArrayList<Integer> list) { // find average of y pixels from drawing
  int avg = 0;
  int size = list.size();
  for (int i = 0; i < size; i ++) {
    avg += list.get(i);
  }
  avg = avg/size;
  return avg;
}

public PImage crop(PImage img) { //crops image from camera to get just the slide
  PImage cropped = img.get(160, 325, 640, 480);
  //cropped.save("cropped.jpg");
  return cropped;
}

public float[] processImage(PImage img, PImage modImg, Boolean isWav) { //takes the image from the folder changes all red pixels to green and returns float array of drawn wave
  modImg.loadPixels(); //load display pixels
  img.loadPixels(); //load images pizels
  img = crop(img);
  img.filter(THRESHOLD, 0.795f);//filters line to black
  //img.save("newimg.jpg");
  float[] wav = new float[camwidth];

  for (int x = 0; x < camwidth; x++) {
    ArrayList<Integer> readBlackPix = new ArrayList<Integer>(); // create list to hold y values for a single x point
    for (int y = 0; y < camheight; y++) {
      int loc = x + y*camwidth; //calculate pixel location

      // Pull out the 3 color components from pixel
      float r = red(img.pixels[loc]);
      float g = green(img.pixels[loc]);
      float b = blue(img.pixels[loc]);

      // Change red pixels to green to show that it was read
      if (r < 10 && b < 10 && g < 10) {
        r=0;
        b=0;
        g=255;
        readBlackPix.add(y); //add the y value to the list
      }

      // Change displayed pixel to represent coordinates counted
      modImg.pixels[loc] =  color(r, g, b);
    }
    if (readBlackPix.isEmpty()) {
      wav[x]=0;
    } else {
      int avg = findAvgY(readBlackPix);
      float avgFl;
      if (isWav) {
        avgFl = map(avg, camheight, 0, -1, 1);//very confused why it's flipped but that's how the numbers work out
      } else {
        avgFl = map(avg, 0, camheight, 0, 1000);//very confused why it's flipped but that's how the numbers work out
      }
      wav[x] = avgFl;
    }
  }
  modImg.updatePixels();
  return wav;
}

public float[] processWavImage() { // feeds in wavImg names to image processing
  return processImage(wavImg, modWavImg, true);
}

public boolean isOnStraight(float f1, float f2, float f3) { //returns a value is surrounded by two like values
  int i1 = Math.round(f1);
  int i2 = Math.round(f2);
  int i3 = Math.round(f3);
  if ((i1 == i2) && (i2 == i3)) {
    return true;
  } else {
    return false;
  }
}

public float[] processEnvImage() { //feeds in env imgs to processing function and returns splits
  float[] splits = new float[2];
  float[] scan = processImage(envImg, modEnvImg, false);
  int counter = 1;
  while (!isOnStraight(scan[counter-1], scan[counter], scan[counter+1])) {
    counter++;
  }
  splits[0] = map(counter, 0, camwidth, 0, 100);
  while (isOnStraight(scan[counter-1], scan[counter], scan[counter+1])) {
    counter++;
    if (counter == (scan.length - 1)) {
      break;
    }
  }
  splits[1] =  map(counter, 0, camwidth, 100, 0);
  return splits;
}

public void printFlArr(float[] wav) { //Print float array
  for (int i = 0; i < width; i ++) {
    println(i + " " + wav[i]);
    delay(100);
  }
}
PImage imageMode; 

public void initImgFromFile(String imgName) {
  imageMode = loadImage(imgName);
  imageMode.resize(640, 480);
}

public ArrayList<float[]> processMultiImage(PImage img) {
  img.loadPixels(); //load images pizels
  int imgWidth = img.width;
  int imgHeight = img.height;

  float[] redWav = new float[imgWidth];
  float[] greenWav = new float[imgWidth];
  float[] blueWav = new float[imgWidth];

  for (int x = 0; x < imgWidth; x++) {
    Integer redPix = 0;
    Integer greenPix = 0;
    Integer bluePix = 0;

    for (int y = 0; y < imgHeight; y++) {
      int loc = x + y*imgWidth; //calculate pixel location

      // Pull out the 3 color components from pixel
      float r = red(img.pixels[loc]);
      float g = green(img.pixels[loc]);
      float b = blue(img.pixels[loc]);

      // Change red pixels to green to show that it was read
      if (g >= b && g >= r) {
        greenPix++;
      } else if (b >= r && b >= g) {
        bluePix++;
      } else if (r >= b && r >= g) {
        redPix++;
      }
    }
    redWav[x] = map(redPix, 0, imgHeight, 1, -1);
    greenWav[x] = map(greenPix, 0, imgHeight, 1, -1);
    blueWav[x] = map(bluePix, 0, imgHeight, 1, -1);
  }
  ArrayList<float[]> returnThis = new ArrayList<float[]>();
  returnThis.add(redWav);
  returnThis.add(greenWav);
  returnThis.add(blueWav);

  return returnThis;
}

public void wait(int time) {
  int start = millis();
  while (millis() <= start+time) {
  }
}

//come back to this later it kinda works but ultimately unimplemented with this version/ui
//float adjacent440(AudioSample sample) {
//  playWav(sample);
//  PitchDetector roughMatinee = new PitchDetector(this, 0.8);
//  roughMatinee.input(sample);
//  float[] pitchAndConfidence = new float[2];
//  wait(300);
//  float pitch = roughMatinee.analyze(pitchAndConfidence);
//  wait(300);
//  while (pitchAndConfidence[1] < 0 && pitchAndConfidence[0] != 0.0) {
//    pitch = roughMatinee.analyze(pitchAndConfidence);
//    wait(10);
//  }
//  float ogPitch = pitch;
//  print(ogPitch);
//  float rateAdjust = (440.0 / ogPitch)*0.7;
//  playWav(sample, rateAdjust);
//  wait(300);
//  pitch = roughMatinee.analyze(pitchAndConfidence);
//  wait(300);
//  while (pitchAndConfidence[1] < 0 || pitchAndConfidence[0] <= ogPitch) {
//    playWav(sample, rateAdjust);
//    wait(300);
//    pitch = roughMatinee.analyze(pitchAndConfidence);
//    wait(300);
//  }
//  println(pitch);
//  return rateAdjust;
//}
// GUI AutoGenSlop For Non Main Windows

boolean helpOpen = false;
boolean envOpen = false;
boolean wavOpen = false;
boolean imgOpen = false;

// 
// Help Menu
//

synchronized public void help_draw(PApplet appc, GWinData data) {
  appc.background(230);
}

public void closingHelper(GWindow window) { //_CODE_:envWindow:608261:
  helpOpen=false;
} //_CODE_:envWindow:608261:

GWindow helpMenu;
GImageButton helpMenuImg;

public void createHelpGUI() {
  helpMenu = GWindow.getWindow(this, "Help", 50, 0, 240, 480, JAVA2D);
  helpMenu.noLoop();
  helpMenu.setActionOnClose(G4P.CLOSE_WINDOW);
  helpMenu.addDrawHandler(this, "help_draw");
  helpMenu.addOnCloseHandler(this, "closingHelper");
  helpMenuImg = new GImageButton(helpMenu, 0, 0, new String[] { "HelpMenu.png", "HelpMenu.png", "HelpMenu.png" } );
  helpMenu.loop();
  helpOpen=true;
}

// 
// Envelope Editor
//

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:envWindow:707014:
  appc.background(143, 3, 3);
} //_CODE_:envWindow:707014:

public void closingEnv(GWindow window) { //_CODE_:envWindow:608261:
  closingEnv();
} //_CODE_:envWindow:608261:

public void checkbox1_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkbox1:403739:
  deviceControlEnv(event);
} //_CODE_:checkbox1:403739:

public void custom_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:custom_slider1:443042:
  sliderUpdate(source, event, 0);
} //_CODE_:custom_slider1:443042:

public void custom_slider2_change1(GCustomSlider source, GEvent event) { //_CODE_:custom_slider2:875688:
  sliderUpdate(source, event, 1);
} //_CODE_:custom_slider2:875688:

public void custom_slider3_change1(GCustomSlider source, GEvent event) { //_CODE_:custom_slider3:577796:
  sliderUpdate(source, event, 2);
} //_CODE_:custom_slider3:577796:

public void option1_clicked1(GOption source, GEvent event) { //_CODE_:sustain:236083:
  sustainMode(event);
} //_CODE_:sustain:236083:

public void option2_clicked1(GOption source, GEvent event) { //_CODE_:sliderRatios:316247:
  sliderModeEnv(event);
} //_CODE_:sliderRatios:316247:

public void option1_clicked2(GOption source, GEvent event) { //_CODE_:option1:402650:
  envModeReset(event);
} //_CODE_:option1:402650:

public void imgButton1_click2(GImageButton source, GEvent event) { //_CODE_:hideAllEnv:656167:
} //_CODE_:hideAllEnv:656167:

public void imgButton2_click1(GImageButton source, GEvent event) { //_CODE_:hideSlidersEnv:513038:
} //_CODE_:hideSlidersEnv:513038:

GWindow envWindow;
GCheckbox checkbox1;
GCustomSlider custom_slider1;
GCustomSlider custom_slider2;
GCustomSlider custom_slider3;
GLabel attack;
GLabel susText;
GLabel relText;
GToggleGroup togGroup1;
GOption sustain;
GOption sliderRatios;
GOption option1;
GImageButton hideAllEnv;
GImageButton hideSlidersEnv;

public void createEnvGUI() {
  envWindow = GWindow.getWindow(this, "Envelope Editor", 25, 650, 290, 241, JAVA2D);
  envWindow.noLoop();
  envWindow.setActionOnClose(G4P.CLOSE_WINDOW);
  envWindow.addDrawHandler(this, "win_draw1");
  envWindow.addOnCloseHandler(this, "closingEnv");
  checkbox1 = new GCheckbox(envWindow, 166, 22, 108, 22);
  checkbox1.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkbox1.setText("Device Control");
  checkbox1.setLocalColorScheme(GCScheme.SCHEME_8);
  checkbox1.setOpaque(false);
  checkbox1.addEventHandler(this, "checkbox1_clicked1");
  checkbox1.setSelected(true);
  custom_slider1 = new GCustomSlider(envWindow, 10, 69, 266, 50, "red_yellow18px");
  custom_slider1.setShowLimits(true);
  custom_slider1.setLimits(5, 0, 10);
  custom_slider1.setNbrTicks(11);
  custom_slider1.setStickToTicks(true);
  custom_slider1.setShowTicks(true);
  custom_slider1.setNumberFormat(G4P.INTEGER, 0);
  custom_slider1.setLocalColorScheme(GCScheme.SCHEME_8);
  custom_slider1.setOpaque(false);
  custom_slider1.addEventHandler(this, "custom_slider1_change1");
  custom_slider2 = new GCustomSlider(envWindow, 10, 127, 266, 50, "red_yellow18px");
  custom_slider2.setShowLimits(true);
  custom_slider2.setLimits(5, 0, 10);
  custom_slider2.setNbrTicks(11);
  custom_slider2.setStickToTicks(true);
  custom_slider2.setShowTicks(true);
  custom_slider2.setNumberFormat(G4P.INTEGER, 0);
  custom_slider2.setLocalColorScheme(GCScheme.SCHEME_8);
  custom_slider2.setOpaque(false);
  custom_slider2.addEventHandler(this, "custom_slider2_change1");
  custom_slider3 = new GCustomSlider(envWindow, 10, 183, 266, 50, "red_yellow18px");
  custom_slider3.setShowLimits(true);
  custom_slider3.setLimits(5, 0, 10);
  custom_slider3.setNbrTicks(11);
  custom_slider3.setStickToTicks(true);
  custom_slider3.setShowTicks(true);
  custom_slider3.setNumberFormat(G4P.INTEGER, 0);
  custom_slider3.setLocalColorScheme(GCScheme.SCHEME_8);
  custom_slider3.setOpaque(false);
  custom_slider3.addEventHandler(this, "custom_slider3_change1");
  attack = new GLabel(envWindow, 10, 110, 265, 20);
  attack.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  attack.setText("Attack");
  attack.setLocalColorScheme(GCScheme.SCHEME_15);
  attack.setOpaque(false);
  susText = new GLabel(envWindow, 10, 167, 266, 20);
  susText.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  susText.setText("Sustain");
  susText.setLocalColorScheme(GCScheme.SCHEME_15);
  susText.setOpaque(false);
  relText = new GLabel(envWindow, 8, 218, 274, 20);
  relText.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  relText.setText("Release");
  relText.setLocalColorScheme(GCScheme.SCHEME_15);
  relText.setOpaque(false);
  togGroup1 = new GToggleGroup();
  sustain = new GOption(envWindow, 15, 14, 120, 20);
  sustain.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  sustain.setText("Sustain Mode");
  sustain.setLocalColorScheme(GCScheme.SCHEME_13);
  sustain.setOpaque(false);
  sustain.addEventHandler(this, "option1_clicked1");
  sliderRatios = new GOption(envWindow, 15, 37, 120, 20);
  sliderRatios.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  sliderRatios.setText("Use Slider Ratios");
  sliderRatios.setLocalColorScheme(GCScheme.SCHEME_10);
  sliderRatios.setOpaque(false);
  sliderRatios.addEventHandler(this, "option2_clicked1");
  option1 = new GOption(envWindow, 85, 400, 120, 20);
  option1.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  option1.setText("option text");
  option1.setOpaque(false);
  option1.addEventHandler(this, "option1_clicked2");
  togGroup1.addControl(sustain);
  togGroup1.addControl(sliderRatios);
  togGroup1.addControl(option1);
  option1.setSelected(true);
  hideAllEnv = new GImageButton(envWindow, 0, 0, 289, 241, new String[] { "EnvHideNonDev.png", "EnvHideNonDev.png", "EnvHideNonDev.png" } );
  hideAllEnv.addEventHandler(this, "imgButton1_click2");
  hideSlidersEnv = new GImageButton(envWindow, 0, 0, 289, 241, new String[] { "EnvHideSliders.png", "EnvHideSliders.png", "EnvHideSliders.png" } );
  hideSlidersEnv.addEventHandler(this, "imgButton2_click1");
  envWindow.loop();
  sustain.setVisible(false);
  sliderRatios.setVisible(false);
  envOpen = true;
}

// 
// Waveform Editor
//
synchronized public void waveditordraw(PApplet appc, GWinData data) { //_CODE_:wavWindow:973281:
  appc.background(143, 3, 3);
} //_CODE_:wavWindow:973281:

public void closingWav(GWindow window) { //_CODE_:envWindow:608261:
  closingWav();
}

public void wavdevice1_clicked1(GOption source, GEvent event) { //_CODE_:wavdevice1:252560:
  if (event == GEvent.SELECTED) {
    tonalControl();
  }
} //_CODE_:wavdevice1:252560:

public void pitchmode_clicked1(GOption source, GEvent event) { //_CODE_:pitchmode:772210:
  if (event == GEvent.SELECTED) {
    atonalControl();
  }
} //_CODE_:pitchmode:772210:

public void pitch_change1(GCustomSlider source, GEvent event) { //_CODE_:pitch:634832:
  freqSlider(source, event);
} //_CODE_:pitch:634832:

public void sinwave_clicked1(GOption source, GEvent event) { //_CODE_:sinwave:493274:
  if (event == GEvent.SELECTED) {
    defaultSin();
  }
} //_CODE_:sinwave:493274:

public void squarewav_clicked1(GOption source, GEvent event) { //_CODE_:squarewav:868981:
  if (event == GEvent.SELECTED) {
    defaultSqr();
  }
} //_CODE_:squarewav:868981:

public void trianglewav_clicked1(GOption source, GEvent event) { //_CODE_:trianglewav:982005:
  if (event == GEvent.SELECTED) {
    defaultTri();
  }
} //_CODE_:trianglewav:982005:

public void sawwav_clicked1(GOption source, GEvent event) { //_CODE_:sawwav:860623:
  if (event == GEvent.SELECTED) {
    defaultSaw();
  }
} //_CODE_:sawwav:860623:

public void rampwav_clicked1(GOption source, GEvent event) { //_CODE_:rampwav:647942:
  if (event == GEvent.SELECTED) {
    defaultRamp();
  }
} //_CODE_:rampwav:647942:

public void stepwav_clicked1(GOption source, GEvent event) { //_CODE_:stepwav:750740:
  if (event == GEvent.SELECTED) {
    defaultStep();
  }
} //_CODE_:stepwav:750740:

public void nowav_clicked1(GOption source, GEvent event) { //_CODE_:nowav:484575:
  println("nowav - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:nowav:484575:

public void wavcontrol_clicked1(GOption source, GEvent event) { //_CODE_:wavcontrol:638305:
  if (event == GEvent.SELECTED) {
    wavDeviceControlOn();
  }
} //_CODE_:wavcontrol:638305:

public void defaultwavs_clicked1(GOption source, GEvent event) { //_CODE_:defaultwavs:227314:
  if (event == GEvent.SELECTED) {
    wavDeviceControlOff();
  }
} //_CODE_:defaultwavs:227314:

public void reddefaultwav_click1(GImageButton source, GEvent event) { //_CODE_:reddefaultwav:743207:
  println("reddefaultwav - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:reddefaultwav:743207:

public void greystuff_click2(GImageButton source, GEvent event) { //_CODE_:greystuff:598096:
  println("imgButton1 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:greystuff:598096:

public void wavlock_click2(GImageButton source, GEvent event) { //_CODE_:wavlock:363349:
  println("wavlock - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:wavlock:363349:

public void sliderwavhider_click2(GImageButton source, GEvent event) { //_CODE_:sliderwavhider:617266:
  println("sliderwavhider - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:sliderwavhider:617266:


public void createWavGUI() {
wavWindow = GWindow.getWindow(this, "Waveform Editor", 1150, 500, 390, 300, JAVA2D);
  wavWindow.noLoop();
  wavWindow.setActionOnClose(G4P.CLOSE_WINDOW);
  wavWindow.addDrawHandler(this, "waveditordraw");
  wavWindow.addOnCloseHandler(this, "closingWav");
  waveditoroptions = new GToggleGroup();
  wavdevice1 = new GOption(wavWindow, 215, 15, 140, 20);
  wavdevice1.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  wavdevice1.setText("Tonal Device Control");
  wavdevice1.setLocalColorScheme(GCScheme.SCHEME_8);
  wavdevice1.setOpaque(false);
  wavdevice1.addEventHandler(this, "wavdevice1_clicked1");
  pitchmode = new GOption(wavWindow, 30, 15, 170, 20);
  pitchmode.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  pitchmode.setText("Atonal Frequency Control");
  pitchmode.setLocalColorScheme(GCScheme.SCHEME_9);
  pitchmode.setOpaque(false);
  pitchmode.addEventHandler(this, "pitchmode_clicked1");
  waveditoroptions.addControl(wavdevice1);
  wavdevice1.setSelected(true);
  waveditoroptions.addControl(pitchmode);
  pitch = new GCustomSlider(wavWindow, 30, 44, 328, 40, "red_yellow18px");
  pitch.setLimits(1, 0, 2);
  pitch.setNumberFormat(G4P.INTEGER, 0);
  pitch.setLocalColorScheme(GCScheme.SCHEME_8);
  pitch.setOpaque(false);
  pitch.addEventHandler(this, "pitch_change1");
  wavgroup = new GToggleGroup();
  sinwave = new GOption(wavWindow, 25, 184, 120, 20);
  sinwave.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  sinwave.setOpaque(false);
  sinwave.addEventHandler(this, "sinwave_clicked1");
  squarewav = new GOption(wavWindow, 25, 236, 120, 20);
  squarewav.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  squarewav.setOpaque(false);
  squarewav.addEventHandler(this, "squarewav_clicked1");
  trianglewav = new GOption(wavWindow, 145, 184, 120, 20);
  trianglewav.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  trianglewav.setOpaque(false);
  trianglewav.addEventHandler(this, "trianglewav_clicked1");
  sawwav = new GOption(wavWindow, 145, 236, 120, 20);
  sawwav.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  sawwav.setOpaque(false);
  sawwav.addEventHandler(this, "sawwav_clicked1");
  rampwav = new GOption(wavWindow, 265, 184, 100, 20);
  rampwav.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  rampwav.setOpaque(false);
  rampwav.addEventHandler(this, "rampwav_clicked1");
  stepwav = new GOption(wavWindow, 265, 236, 100, 20);
  stepwav.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  stepwav.setOpaque(false);
  stepwav.addEventHandler(this, "stepwav_clicked1");
  nowav = new GOption(wavWindow, 540, 235, 120, 20);
  nowav.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  nowav.setText("option text");
  nowav.setOpaque(false);
  nowav.addEventHandler(this, "nowav_clicked1");
  wavgroup.addControl(sinwave);
  wavgroup.addControl(squarewav);
  wavgroup.addControl(trianglewav);
  wavgroup.addControl(sawwav);
  wavgroup.addControl(rampwav);
  wavgroup.addControl(stepwav);
  wavgroup.addControl(nowav);
  nowav.setSelected(true);
  Wavdevicegroup = new GToggleGroup();
  wavcontrol = new GOption(wavWindow, 20, 100, 120, 20);
  wavcontrol.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  wavcontrol.setText("Device Control");
  wavcontrol.setLocalColorScheme(GCScheme.SCHEME_8);
  wavcontrol.setOpaque(false);
  wavcontrol.addEventHandler(this, "wavcontrol_clicked1");
  defaultwavs = new GOption(wavWindow, 20, 127, 180, 20);
  defaultwavs.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  defaultwavs.setText("Use Defualt Waveforms");
  defaultwavs.setLocalColorScheme(GCScheme.SCHEME_14);
  defaultwavs.setOpaque(false);
  defaultwavs.addEventHandler(this, "defaultwavs_clicked1");
  Wavdevicegroup.addControl(wavcontrol);
  wavcontrol.setSelected(true);
  Wavdevicegroup.addControl(defaultwavs);
  reddefaultwav = new GImageButton(wavWindow, 43, 170, new String[] { "redstuff.png", "redstuff.png", "redstuff.png" } );
  reddefaultwav.addEventHandler(this, "reddefaultwav_click1");
  greystuff = new GImageButton(wavWindow, 43, 170, new String[] { "greyed stuff.png", "greyed stuff.png", "greyed stuff.png" } );
  greystuff.addEventHandler(this, "greystuff_click2");
  wavlock = new GImageButton(wavWindow, 0, 0, 390, 300, new String[] { "WavLockOverlay.png", "WavLockOverlay.png", "WavLockOverlay.png" } );
  wavlock.addEventHandler(this, "wavlock_click2");
  sliderwavhider = new GImageButton(wavWindow, 0, 0, 390, 88, new String[] { "SliderWav.png", "SliderWav.png", "SliderWav.png" } );
  sliderwavhider.addEventHandler(this, "sliderwavhider_click2");
  wavWindow.loop();
  wavOpen=true;
}

GWindow wavWindow;
GToggleGroup waveditoroptions; 
GOption wavdevice1; 
GOption pitchmode; 
GCustomSlider pitch; 
GToggleGroup wavgroup; 
GOption sinwave; 
GOption squarewav; 
GOption trianglewav; 
GOption sawwav; 
GOption rampwav; 
GOption stepwav; 
GOption nowav; 
GToggleGroup Wavdevicegroup; 
GOption wavcontrol; 
GOption defaultwavs; 
GImageButton reddefaultwav; 
GImageButton greystuff; 
GImageButton wavlock; 
GImageButton sliderwavhider; 
PImage filereset = createImage(camwidth, camheight, RGB);

public float[] genSinWav() { //create sin wav arr
  float[] sinewave = new float[640];

  for (int i = 0; i < 640; i++) {
    sinewave[i] = -sin(TWO_PI*i/640);
  }
  return sinewave;
}

public float[] genBasicEnv() { //create reset env
  float attackTime = 0.1f;
  float sustainTime = 0.5f;
  float releaseTime = 0.4f;
  return new float[]{attackTime, sustainTime, releaseTime};
}

public void clearCache() {
  resetWav();
  resetEnv();
  println("Image Cache Cleared");
}

public void clearActiveSamples() {
  for (AudioSample s : endSus) {
    s.stop();
  }
  endSus = new ArrayList<AudioSample>();
}
//Waveform Editor
public void openWavMenu() {
  if (wavOpen == false) {
    createWavGUI();
  }
}

public void closingWav() {
  wavOpen = false;
}

float[] defaultWav = resetSin;

public void wavDeviceControlOn() {
  wavControl = true;
  nowav.setSelected(true);
  greystuff.setVisible(true);
  wavlock.setVisible(true);
}

public void wavDeviceControlOff() {
  wavControl = false;
  sinwave.setSelected(true);
  greystuff.setVisible(false);
  wavlock.setVisible(false);
}

public void tonalControl() {
  sliderwavhider.setVisible(true);
  pitch.setLimits(1, 0, 2); // fix limits
  wavMult=1;
}

public void atonalControl() {
  sliderwavhider.setVisible(false);
  pitch.setLimits(1, 0, 2); // fix limits
  wavMult=1;
}

public void freqSlider(GCustomSlider source, GEvent event) {
  if (event == GEvent.RELEASED) {
    wavMult = source.getValueF();
  }
}

//Wav Generation Functions
public void defaultSin() {
  defaultWav = resetSin;
}

public void defaultSqr() {
  float[] sqrwav = new float[640];

  for (int i = 0; i < 640; i++) {
    if (i < 320) {
      sqrwav[i] = -1;
    } else {
      sqrwav[i] = 1;
    }
  }
  defaultWav=sqrwav;
}

public void defaultTri() {
  float[] triwav = new float[640];
  int counter = 0;
  for (int i = 0; i < 640; i++) {
    if (i == 0) {
      counter = 0;
    } else if (i < 160) {
      counter +=1;
    } else if (i < 480) {
      counter -=1;
      triwav[i] = counter;
    } else {
      counter +=1;
    }
    triwav[i] = map(counter, -159, 159, 1, -1);
  }
  defaultWav=triwav;
}

public void defaultSaw() {
  float[] sawwav = new float[640];
  int counter = 320;
  for (int i = 0; i < 640; i++) {
    counter -=1;
    sawwav[i] = map(counter, -319, 319, 1, -1);
  }
  defaultWav = sawwav;
}

public void defaultRamp() {
  float[] rampwav = new float[640];
  int counter = -320;
  for (int i = 0; i < 640; i++) {
    counter +=1;
    rampwav[i] = map(counter, -319, 319, 1, -1);
  }
  defaultWav=rampwav;
}

public void defaultStep() {
  float[] stepwav = new float[640];
  int counter = 0;
  int step = 0;
  for (int i = 0; i < 640; i++) {
    if (step != 16) {
      step++;
    } else {
      counter++;
      step=0;
    }
    stepwav[i] = map(counter, 0, 39, 1, -1);
  }
  defaultWav=stepwav;
}

// Envelope Editor
public void openEnvMenu() {
  if (envOpen == false) {
    createEnvGUI();
  }
}

public void closingEnv() {
  susMode = false;
  sliderMode = false;
  clearEnv = true;
  envOpen=false;
}

public void deviceControlEnv(GEvent event) {
  if (event == GEvent.DESELECTED) {
    hideAllEnv.setVisible(false);
    option1.setSelected(true);
    sustain.setVisible(true);
    sliderRatios.setVisible(true);
  } else if (event == GEvent.SELECTED) {
    sustain.setVisible(false);
    sliderRatios.setVisible(false);
    hideAllEnv.setVisible(true);
    option1.setSelected(true);
    hideSlidersEnv.setVisible(true);
    custom_slider1.setLimits(5, 0, 10);
    custom_slider2.setLimits(5, 0, 10);
    custom_slider3.setLimits(5, 0, 10);
    susMode = false;
    sliderMode = false;
    clearEnv = true;
  }
}

public void sustainMode(GEvent event) {
  if (event == GEvent.SELECTED) {
    hideSlidersEnv.setVisible(true);
    custom_slider1.setLimits(5, 0, 10);
    custom_slider2.setLimits(5, 0, 10);
    custom_slider3.setLimits(5, 0, 10);
    susMode = true;
    clearEnv = false;
    sliderMode = false;
  }
}

public void sliderModeEnv(GEvent event) {
  if (event == GEvent.SELECTED) {
    hideSlidersEnv.setVisible(false);
    custom_slider1.setLimits(5, 0, 10);
    custom_slider2.setLimits(5, 0, 10);
    custom_slider3.setLimits(5, 0, 10);
    sliderVals = new int[]{5, 5, 5};
    susMode = false;
    clearEnv = false;
    sliderMode = true;
  }
}

public void envModeReset(GEvent event) {
  if (event == GEvent.SELECTED) {
    hideSlidersEnv.setVisible(true);
    custom_slider1.setLimits(5, 0, 10);
    custom_slider2.setLimits(5, 0, 10);
    custom_slider3.setLimits(5, 0, 10);
    susMode = false;
    sliderMode = false;
    clearEnv = true;
  }
}

public void sliderUpdate(GCustomSlider source, GEvent event, int index) {
  if (event == GEvent.RELEASED) {
    sliderVals[index] = source.getValueI();
  }
}

//Help Menu
public void openHelpMenu() {
  if (helpOpen == false) {
    createHelpGUI();
  }
}

//Main Window
public void setModeKnob(GKnob source) {
  mode = source.getValueF();
}

public void setVolKnob(GKnob source) {
  volume = Math.round(source.getValueI()) * 0.1f;//Round volume
  s.volume(volume);
}


  public void settings() { size(720, 466, JAVA2D); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "smplasketch" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
