/* autogenerated by Processing revision 1307 on 2025-11-18 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import g4p_controls.*;
import ddf.minim.*;
import ddf.minim.ugens.*;
import processing.video.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class smplASketchMinim extends PApplet {





boolean test = false;

//Camera Dimensions Setup
int[] sizeArr = {661, 480};
int camwidth = sizeArr[0];
int camheight = sizeArr[1];

//Minim Setup
Minim minim;
AudioOutput out;
AudioRecorder recorder;

public void setup() {
  //Setup Main Window
  /* size commented out by preprocessor */;
  /* smooth commented out by preprocessor */;
  uiSetup();
  //Img setup(create blank copies for processsion)
  modWavImg = createImage(camwidth, camheight, RGB);
  modCalibImg = createImage(camwidth, camheight, RGB);
  modLFOImg = createImage(camwidth, camheight, RGB);
  initImgFromFile("blank.jpg");
  //Camera Setup
  searchForCamera();
  //clear cache
  clearCache();
  //Setup Envelope Code
  resetEnv();
  //Minim Setup
  minim = new Minim(this);
  out = minim.getLineOut( Minim.MONO, 2048 );
}

public void draw() {
  drawDarkMode(); //Draw background
  setOnDotsVis(); //Set photosynthesis knob lights to off
  screenMode(); //Choose what to display on SmplASketch screen
  playheadAnimation(); //If playhead is on handle animation
}


Capture cam;

public void searchForCamera() { //Camera intialization function
  String[] cameras = Capture.list();

  if (cameras.length == 0) {
    println("There are no cameras available for capture.");
    exit();
  } else {
    println("Available cameras:");
    int setcamIndex = -1;
    for (int i = 0; i < cameras.length; i++) {
      println(cameras[i]);
      if (cameras[i].contains("C270")) {
        setcamIndex = i;
      }
    }
    if (setcamIndex != -1 || test) {//allows the program to run even when device is not connected while testing
      if (test) {
        cam = new Capture(this, 850, 900, "pipeline:avfvideosrc device-index=0", 30);
      } else {
        cam = new Capture(this, 850, 900, "pipeline:avfvideosrc device-index="+setcamIndex, 30);
      }
      cam.start();
    } else {
      //if cam is not connected and is not in test mode turn off program
      wait(5000);
      exit();
    }
  }
}

public void takePicture(String imageName) { //Uses camera to take picture and save to code folder
  if (cam.available() == true) {
    cam.read();
  }
  cam.save(imageName+".jpg");
}

public void wavSnap() { //Captures photo for save slot 1
  takePicture("wav_image");
  wavImg = loadImage("wav_image.jpg");
  clearWav = false;
  wavSlot.setText("In Use");
}

public void lfoSnap() { //Captures photo for save slot 2
  takePicture("lfo_image");
  lfoImg = loadImage("lfo_image.jpg");
  clearLFO = false;
  LFOSlot.setText("In Use");
}
//When key or button on device is pressed control the code base
public void keyPressed() { //test true is for keyboard control test false is ascii to talk to teensy
  if ((test == true && key == 'w')||(test == false && key == '€')) {
    wavSnap();
    println("wavSnap");
  } else if ((test == true && key == 'e')||(test == false && key == 'ƒ')) {
    lfoSnap();
    println("envSnap");
  } else if ((test == true && key == '[')||(test == false && key == '†')) {
    decLFOMult();
    println("decEnv");
  } else if ((test == true && key == ']')||(test == false && key == '‡')) {
    incLFOMult();
    println("incEnv");
  } else if ((test == true && key == '-')||(test == false && key == '‰')) {
    decWavMult();
    println("decWav");
  } else if ((test == true && key == '=')||(test == false && key == '°')) {
    incWavMult();
    println("incWav");
  } else if ((test == true && key == 's')||(test == false && key == 'Œ')) {
    smpl();
    println("smpl");
  } else if ((test == true && key == 'r')||(test == false && key == '™')) {
    resetWav();
    println("resetWav");
  } else if ((test == true && key == 't')||(test == false && key == '◊')) {
    resetLFO();
    println("resetLFO");
  } else if (key == (char)27) {//Escape key always exits program
    clearCache();
    println("Program Exit");
    exit();
  } 
}

//Counters for /\ and \/ buttons on device
public void incWavMult() {
  if (noteIndex < 13) {
    noteIndex++;
    bigtone_slider1.setLimits(noteIndex-1, 0, 12);
  }
}

public void decWavMult() {
  if (noteIndex > 1) {
    noteIndex--;
    bigtone_slider1.setLimits(noteIndex-1, 0, 12);
  }
}

public void incLFOMult() {
  if (lfoMods[0] <= 0.9f) {
    lfoMods[0] += 0.1f;
    lfoLen_slider1.setLimits(lfoMods[0], 0.0f, 1.0f);
  }
}

public void decLFOMult() {
  if (lfoMods[0] >= 0.1f) {
    lfoMods[0] -= 0.1f;
    lfoLen_slider1.setLimits(lfoMods[0], 0.0f, 1.0f);
  }
}
float[] resetSin = genSinWav();
float mode = 0.0f; 
float prevMode = 0.0f;
boolean drawCombWav = true;
boolean drawCombEnv = false;
boolean drawCombLFO = false;
boolean camVsCapCalib = true;
boolean calibMode = false;

PImage camCap;
boolean extraction = false;

public void calibMode() { //Display/functionality of calibration
  takePicture("calib");
  modeDisplay.setText("Calibration");
  PImage camCapMod;
  camCap = loadImage("calib.jpg");
  if (camVsCapCalib) {
    camCapMod = crop(camCap);
  } else {
    camCapMod = threshed(crop(camCap));
  }
  image(camCapMod, 430, 128);
  if (extraction) {
    drawExtract(processCalibImage());
  }
}

//Screen Modes
public void wavMode(float[] wav) { //save slot 1
  drawScreen();
  drawWav(wav);
}

public void envMode(float[] env) { //envelope editor
  drawScreen();
  drawEnv(env);
}

public void lfoMode(float[] lfo) { //save slot 1
  drawScreen();
  drawLFO(lfo);
}

public void comboMode(float[] wav, float[] env, float[] lfo) { //playback display
  drawScreen();
  if (drawCombWav)drawWav(wav);
  if (drawCombEnv)drawEnv(env);
  if (drawCombLFO)drawLFO(lfo);
}

public void imgMode() { //photosynthesis display
  drawScreen();
  ArrayList<float[]> arrList = processMultiImage(imageMode);
  int counter = 0;
  for (float[] f : arrList) { //only draw color wavs that are selected
    if (counter == 0) {
      if (photsynthesisDots[0] == true) drawWav(f, 255, 0, 0);
    } else if (counter == 1) {
      if (photsynthesisDots[2] == true) drawWav(f, 0, 255, 0);
    } else if (counter == 2) {
      if (photsynthesisDots[1] == true) drawWav(f, 0, 0, 255);
    } else if (counter == 3) {
      if (photsynthesisDots[3] == true) drawWav(f, 255, 255, 0);
    } else if (counter == 4) {
      if (photsynthesisDots[4] == true) drawWav(f, 128, 0, 128);
    } else if (counter == 5) {
      if (photsynthesisDots[5] == true) drawWav(f, 255, 165, 0);
    }
    counter++;
  }
}

public void checkMode() { //Checks to see which position the knob is in and sends values into drawing helpers for each mode
  float[] wavtemp;
  float[] envtemp;
  float[] lfotemp;
  if (0.0f == mode || prevMode == 0.0f) {
    if (clearWav && wavControl) {
      wavMode(resetSin);
    } else if (!wavControl) {
      wavMode(defaultWav);
    } else {
      wavMode(processWavImage());
    }
    modeDisplay.setText("Waveform");
    prevMode = 0.0f;
  }
  if (1.0f == mode || prevMode == 1.0f) {
    float[] mappedSliders = new float[]{map(sliderVals[0], 0, 10, 0.f, 1.f), map(sliderVals[1], 0, 10, 0.f, 1.f), map(sliderVals[2], 0, 10, 0.f, 1.f), map(sliderVals[3], 0, 10, 0.f, 1.f)};
    envMode(mappedSliders);
    modeDisplay.setText("Envelope");
    prevMode = 1.0f;
  }
  if (2.0f == mode || prevMode ==2.0f) {
    if (clearLFO && lfoControl) {
      lfoMode(resetSin);
    } else if (!lfoControl) {
      lfoMode(defaultLFO);
    } else {
      lfoMode(processLFOImage());
    }
    modeDisplay.setText("LFO");
    prevMode = 2.0f;
  }
  if (3.0f == mode || prevMode ==3.0f) {
    if (clearWav && wavControl) {
      wavtemp = resetSin;
    } else if (!wavControl) {
      wavtemp = defaultWav;
    } else {
      wavtemp = processWavImage();
    }
    envtemp = new float[]{map(sliderVals[0], 0, 10, 0.f, 1.f), map(sliderVals[1], 0, 10, 0.f, 1.f), map(sliderVals[2], 0, 10, 0.f, 1.f), map(sliderVals[3], 0, 10, 0.f, 1.f)};
    if (clearLFO && lfoControl) {
      lfotemp = resetSin;
    } else if (!lfoControl) {
      lfotemp = defaultLFO;
    } else {
      lfotemp = processLFOImage();
    }
    comboMode(wavtemp, envtemp, lfotemp);
    modeDisplay.setText("Combinatory/Playback");
    prevMode = 3.0f;
  }
  if (4.0f == mode || prevMode ==4.0f) {
    imgMode();
    envtemp = new float[]{map(sliderVals[0], 0, 10, 0.f, 1.f), map(sliderVals[1], 0, 10, 0.f, 1.f), map(sliderVals[2], 0, 10, 0.f, 1.f), map(sliderVals[3], 0, 10, 0.f, 1.f)};
    if(photoEnvDisplay){
    photoEnvMode(envtemp);
    }
    modeDisplay.setText("Photosynthesis");
    prevMode = 4.0f;
  }
}

//sets either regular display mode or calib
public void screenMode() {
if (calibMode) {
    calibMode();
  } else {
    checkMode();
  }
}
int thickStroke = 2;
boolean showPlayLine = false;
int[][] drawColor = {{225, 0, 0}, {0, 0, 225}, {102, 45, 145}};
int screenColorNum = 200;

//Color control
public void setColor(int index, int r, int g, int b) {
  drawColor[index][0] = r;
  drawColor[index][1] = g;
  drawColor[index][2] = b;
}

//Basic draw Functions
public void drawScreen() { //draw blank screen
  fill(screenColorNum);
  rect(420, 120, 670, 325);
}

public void drawDarkMode() {
  background(102);
  noStroke();
  fill(51);
  rect(0, 0, 1512, 57);
  rect(0, 830, 1512, 57);
  fill(200);
  rect(420, 120, 670, 325);
  fill(255, 255, 150);
  rect(246, 467, 57, 57);
}



//Data Mapping
public float[] mappedFlArr(float[] flArr) { //Map wav values to fit the ui screen
  float[] temp = new float[flArr.length];
  for (int i = 0; i < flArr.length; i++) {
    temp[i] = map(flArr[i], -1, 1, 148, 428);
  }
  return temp;
}

public float[] mappedLFOArr(float[] flArr) { //Map wav values to fit the ui screen
  float[] temp = new float[flArr.length];
  for (int i = 0; i < flArr.length; i++) {
    temp[i] = map(flArr[i], -1, 1, 208, 368);
  }
  return temp;
}

public float[] mapEnv(float[] env) { //Map envelope values to fit the ui screen
  float totalTime = env[0]+env[1]+env[2]+env[3];
  float ratio = totalTime/4.0f;
  float attackTime = map(env[0], 0.0f, totalTime, 0, (int)camwidth*ratio);
  float decayTime = map(env[1], 0.0f, totalTime, 0, (int)camwidth*ratio);
  float sustainTime = map(env[2], 0.0f, totalTime, 0, (int)camwidth*ratio);
  float releaseTime = map(env[3], 0.0f, totalTime, 0, (int)camwidth*ratio);
  return new float[]{attackTime, decayTime, sustainTime, releaseTime, ratio};
}

//Draw hlper for calibration extraction
public void drawExtract(float[] wavArr) { //takes wav arr draws it
  stroke(225, 0, 0);
  strokeWeight(thickStroke);
  float[] wav = mappedFlArr(wavArr);
  for (int i = 0; i < wav.length-1; i ++) {
    line(i+430, wav[i], i+431, wav[i+1]);
  }
}
//Draw helpers functions for the 3 main sound data types
public void drawWav(float[] wavArr, int r, int g, int b) { //takes wav arr draws it and takes color parameters
  stroke(r, g, b);
  strokeWeight(thickStroke);
  float[] wav = mappedFlArr(wavArr);
  for (int i = 0; i < wav.length-1; i ++) {
    line(i+430, wav[i], i+431, wav[i+1]);
  }
}

public void drawWav(float[] wavArr) { //takes wav arr draws it as set wav color
  drawWav(wavArr, drawColor[0][0], drawColor[0][1], drawColor[0][2]);
}

public void drawEnv(float[] envArr) { //takes env arr draws it
  stroke(drawColor[1][0], drawColor[1][1], drawColor[1][2]);
  strokeWeight(thickStroke);
  float[] env = mapEnv(envArr);
  line(430, 448, 430+env[0], 200);
  line(430+env[0], 200, 430+env[0]+env[1], 300);
  line(430+env[0]+env[1], 300, 430+env[0]+env[1]+env[2], 300);
  line(430+env[0]+env[1]+env[2], 300, 430+(int)(camwidth*env[4]), 448);
}

public void photoEnvMode(float[] envArr) {
  stroke(0,0,0);
  strokeWeight(thickStroke);
  float[] env = mapEnv(envArr);
  line(430, 448, 430+env[0], 200);
  line(430+env[0], 200, 430+env[0]+env[1], 300);
  line(430+env[0]+env[1], 300, 430+env[0]+env[1]+env[2], 300);
  line(430+env[0]+env[1]+env[2], 300, 430+(int)(camwidth*env[4]), 448);
}

public void drawLFO(float[] lfoArr) { //takes lfo arr draws it
  stroke(drawColor[2][0], drawColor[2][1], drawColor[2][2]);
  strokeWeight(thickStroke);
  float[] lfo = mappedLFOArr(lfoArr);
  if (lfoOn) {
    for (int i = 0; i < lfo.length-1; i ++) {
      line(i+430, lfo[i], i+431, lfo[i+1]);
    }
  } else {
    for (int i = 0; i < lfo.length-1; i ++) {
      line(i+430, 290, i+431, 290);
    }
  }
}

//Animation Drawing
float linecounter = 700;
public void drawGreenLine() {
  stroke(0, 255, 0);
  line((int)432+linecounter, 128, (int)432+linecounter, 448);
  linecounter += (2.7f*(1/envMult));
}

public void playheadAnimation(){
if (showPlayLine && !noShow) {
    if (linecounter < 680) drawGreenLine();
  }
}

//GUI Drawing
public void setAdditionSchemes() {
  dropListRed.setLocalColor(2, color(0, 0, 0));
  dropListBlue.setLocalColor(2, color(0, 0, 0));
  dropListGreen.setLocalColor(2, color(0, 0, 0));
  dropListYellow.setLocalColor(2, color(0, 0, 0));
  dropListPurple.setLocalColor(2, color(0, 0, 0));
  dropListOrange.setLocalColor(2, color(0, 0, 0));
  fileName.setLocalColorScheme(GCScheme.RED_SCHEME);
  fileName.setLocalColor(2, color(255, 0, 0));
  pitch.setLocalColor(2, color(0, 0, 0));
}

public void setOnDotsVis() {
  redon.setVisible(photsynthesisDots[0]);
  blueon.setVisible(photsynthesisDots[1]);
  greenon.setVisible(photsynthesisDots[2]);
  yellowon.setVisible(photsynthesisDots[3]);
  purpleon.setVisible(photsynthesisDots[4]);
  orangeon.setVisible(photsynthesisDots[5]);
}
String saveLoc = "";

public void initImgFromFile(String imgName) {//Warp image to cam dimensions
  imageMode = loadImage(imgName);
  imageMode.resize(camwidth, camheight);
}

public void selectSaveLoc() { //Select export location for mp3/editor files
  selectFolder("Select a folder to process:", "folderSelected");
}

public void folderSelected(File selection) {
  if (selection == null) {
    println("Window was closed or the user hit cancel.");
  } else {
    saveLoc = selection.getAbsolutePath();
    exportLocLabel.setText(getShortFileName(selection.getAbsolutePath()));
  }
}

public void selectPhotosynthesisFile() {//Select image location for PS
  selectInput("Select an image to process:", "fileSelected");
}

public void fileSelected(File selection) {
  if (selection == null) {
    println("Window was closed or the user hit cancel.");
  } else {
    FileName.setText(getShortFileName(selection.getAbsolutePath()));
    imageMode = loadImage(selection.getAbsolutePath());
    imageMode.resize(camwidth, camheight);
    photsynthesisImage = new GImageButton(this, 1241, 662, 218, 159, new String[] { selection.getAbsolutePath(), selection.getAbsolutePath(), selection.getAbsolutePath() } );
  }
}

public String getShortFileName(String selection) { //get a shortened file name to display in ui
  char[] chars = selection.toCharArray();
  int lastSlash = 0;
  for (int i = 0; i < selection.length(); i ++) {
    if (chars[i] == '/') lastSlash = i;
  }
  String modSelection = selection;
  if (lastSlash != 0) {
    modSelection = "";
    for (int i = lastSlash+1; i < selection.length(); i ++) {
      modSelection += chars[i];
    }
  }
  if (modSelection.length() >= 30){
  char[] modchararr = modSelection.toCharArray();
  String temp = "";
  for (int i = 0; i < 30; i ++) {
    temp += modchararr[i];
  }
  temp += "...";
  modSelection = temp;
  }
  return modSelection;
}

public void helpButton() {//link for help button
  link("https://github.com/clarinetgamer/SmplASketch");
}
/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.
 
 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
 // It is safe to enter your event code here
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:backgroundDarkMode:814029:
} //_CODE_:backgroundDarkMode:814029:

public void volknob_turn1(GKnob source, GEvent event) { //_CODE_:volknob:531573:
  setVolKnob(source);
} //_CODE_:volknob:531573:

public void modeknob_turn1(GKnob source, GEvent event) { //_CODE_:modeknob:804666:
  setModeKnob(source);
} //_CODE_:modeknob:804666:

public void attack_slider_change1(GCustomSlider source, GEvent event) { //_CODE_:attack_slider:517428:
  sliderUpdate(source, event, 0);
} //_CODE_:attack_slider:517428:

public void sustain_slider_change1(GCustomSlider source, GEvent event) { //_CODE_:sustain_slider:446330:
  sliderUpdate(source, event, 2);
} //_CODE_:sustain_slider:446330:

public void release_slider_change1(GCustomSlider source, GEvent event) { //_CODE_:release_slider:235931:
  sliderUpdate(source, event, 3);
} //_CODE_:release_slider:235931:

public void redWavOverlay_click2(GImageButton source, GEvent event) { //_CODE_:redWavOverlay:451286:
} //_CODE_:redWavOverlay:451286:

public void sinButt_clicked1(GOption source, GEvent event) { //_CODE_:sinButt:511167:
  sinWavSelect(event);
} //_CODE_:sinButt:511167:

public void triButt_clicked1(GOption source, GEvent event) { //_CODE_:triButt:532566:
  triWavSelect(event);
} //_CODE_:triButt:532566:

public void sqrButt_clicked1(GOption source, GEvent event) { //_CODE_:sqrButt:650107:
  sqrWavSelect(event);
} //_CODE_:sqrButt:650107:

public void sawButt_clicked1(GOption source, GEvent event) { //_CODE_:sawButt:584368:
  sawWavSelect(event);
} //_CODE_:sawButt:584368:

public void stepButt_clicked1(GOption source, GEvent event) { //_CODE_:stepButt:289370:
  stepWavSelect(event);
} //_CODE_:stepButt:289370:

public void rampButt_clicked1(GOption source, GEvent event) { //_CODE_:rampButt:866973:
  rampWavSelect(event);
} //_CODE_:rampButt:866973:

public void DevControWav_clicked1(GOption source, GEvent event) { //_CODE_:DevControWav:234113:
  wavDeviceOn(event);
} //_CODE_:DevControWav:234113:

public void DefaultWav_clicked1(GOption source, GEvent event) { //_CODE_:DefaultWav:337021:
  wavDeviceOff(event);
} //_CODE_:DefaultWav:337021:

public void freq_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:freq_slider1:305465:
  pitchFineAdjust(source, event);
} //_CODE_:freq_slider1:305465:

public void bigtone_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:bigtone_slider1:797863:
  pitchCoarseAdjust(source, event);
} //_CODE_:bigtone_slider1:797863:

public void lfored_click2(GImageButton source, GEvent event) { //_CODE_:lfored:748321:
} //_CODE_:lfored:748321:

public void lfosin_clicked1(GOption source, GEvent event) { //_CODE_:lfosin:814746:
  sinLFOSelect(event);
} //_CODE_:lfosin:814746:

public void lfosqr_clicked1(GOption source, GEvent event) { //_CODE_:lfosqr:682065:
  sqrLFOSelect(event);
} //_CODE_:lfosqr:682065:

public void lfotri_clicked1(GOption source, GEvent event) { //_CODE_:lfotri:477914:
  triLFOSelect(event);
} //_CODE_:lfotri:477914:

public void lfosaw_clicked1(GOption source, GEvent event) { //_CODE_:lfosaw:915018:
  sawLFOSelect(event);
} //_CODE_:lfosaw:915018:

public void lforamp_clicked1(GOption source, GEvent event) { //_CODE_:lforamp:354875:
  rampLFOSelect(event);
} //_CODE_:lforamp:354875:

public void lfostep_clicked1(GOption source, GEvent event) { //_CODE_:lfostep:806592:
  stepLFOSelect(event);
} //_CODE_:lfostep:806592:

public void lfosaveslot_clicked1(GOption source, GEvent event) { //_CODE_:lfosaveslot:840679:
  lfoDeviceOn(event);
} //_CODE_:lfosaveslot:840679:

public void defaulttheLfo_clicked1(GOption source, GEvent event) { //_CODE_:defaulttheLFO:562707:
  lfoDeviceOff(event);
} //_CODE_:defaulttheLFO:562707:

public void lfoLen_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:lfoLen_slider1:956883:
  sliderUpdateLFO(source, event, 0);
} //_CODE_:lfoLen_slider1:956883:

public void lowFreq_slider2_change1(GCustomSlider source, GEvent event) { //_CODE_:lowFreq_slider2:922769:
  sliderUpdateLFO(source, event, 1);
} //_CODE_:lowFreq_slider2:922769:

public void rangeFreq_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:highFreq_slider1:611418:
  sliderUpdateLFO(source, event, 2);
} //_CODE_:highFreq_slider1:611418:

public void calibration_clicked1(GCheckbox source, GEvent event) { //_CODE_:calibration:261462:
  calibrationOn(event);
} //_CODE_:calibration:261462:

public void showCam_clicked1(GOption source, GEvent event) { //_CODE_:showCam:597026:
  calibCam(event);
} //_CODE_:showCam:597026:

public void capturecali_clicked1(GOption source, GEvent event) { //_CODE_:capturecali:200276:
  calibCapture(event);
} //_CODE_:capturecali:200276:

public void showExtract_clicked1(GCheckbox source, GEvent event) { //_CODE_:showExtract:883300:
  calibExtract(event);
} //_CODE_:showExtract:883300:

public void threshold_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:threshold_slider1:865497:
  thresholdMod(source, event);
} //_CODE_:threshold_slider1:865497:

public void zoom_slider2_change1(GCustomSlider source, GEvent event) { //_CODE_:zoom_slider2:491766:
  shiftMod(source, event);
} //_CODE_:zoom_slider2:491766:

public void envClear_click3(GImageButton source, GEvent event) { //_CODE_:envClear:356676:
  envRButton(event);
} //_CODE_:envClear:356676:

public void browseButton_click1(GImageButton source, GEvent event) { //_CODE_:browseButton:763920:
  psSearchFile(event);
} //_CODE_:browseButton:763920:

public void smplButton1_click2(GImageButton source, GEvent event) { //_CODE_:smplButton:548598:
  smplUIButton(event);
} //_CODE_:smplButton:548598:

public void wavClear_click2(GImageButton source, GEvent event) { //_CODE_:wavClear:280934:
  wavRButton(event);
} //_CODE_:wavClear:280934:

public void resetCalib_click2(GImageButton source, GEvent event) { //_CODE_:resetCalib:215921:
  calibRButton(event);
} //_CODE_:resetCalib:215921:

public void clearTheLFO_click2(GImageButton source, GEvent event) { //_CODE_:clearTheLFO:939396:
  lfoRButton(event);
} //_CODE_:clearTheLFO:939396:

public void ScreenColor_change1(GCustomSlider source, GEvent event) { //_CODE_:screenColor:548097:
  screenColorControl(source, event);
} //_CODE_:screenColor:548097:

public void lfoColor_change1(GCustomSlider source, GEvent event) { //_CODE_:lfoColor:598006:
  colorControl(source, event, 2);
} //_CODE_:lfoColor:598006:

public void envColor_change1(GCustomSlider source, GEvent event) { //_CODE_:envColor:742676:
  colorControl(source, event, 1);
} //_CODE_:envColor:742676:

public void wavColor_change1(GCustomSlider source, GEvent event) { //_CODE_:wavColor:859202:
  colorControl(source, event, 0);
} //_CODE_:wavColor:859202:

public void thickness_change1(GCustomSlider source, GEvent event) { //_CODE_:thickness:554351:
  strokeSet(source, event);
} //_CODE_:thickness:554351:

public void browseExport_click2(GImageButton source, GEvent event) { //_CODE_:browseExport:709904:
  setExport(event);
} //_CODE_:browseExport:709904:

public void fileName_change1(GTextField source, GEvent event) { //_CODE_:fileName:663355:
  centerFileName(source, event);
} //_CODE_:fileName:663355:

public void saveButt_click2(GImageButton source, GEvent event) { //_CODE_:saveButt:878919:
  println("saveButt - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:saveButt:878919:

public void backButt_click1(GImageButton source, GEvent event) { //_CODE_:backButt:551776:
  println("backButt - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:backButt:551776:

public void playButt_click1(GImageButton source, GEvent event) { //_CODE_:playButt:310979:
  println("playButt - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:playButt:310979:

public void stopButt_click2(GImageButton source, GEvent event) { //_CODE_:stopButt:855839:
  println("stopButt - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:stopButt:855839:

public void forButt_click2(GImageButton source, GEvent event) { //_CODE_:forbutt:485441:
  println("forbutt - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:forbutt:485441:

public void helpButt_click2(GImageButton source, GEvent event) { //_CODE_:helpButt:585685:
  helpLink(event);
} //_CODE_:helpButt:585685:

public void preset_click2(GImageButton source, GEvent event) { //_CODE_:preset:485718:
  println("preset - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:preset:485718:

public void photsynthesisImage_click2(GImageButton source, GEvent event) { //_CODE_:photsynthesisImage:477057:
} //_CODE_:photsynthesisImage:477057:

public void redTogButton1_click1(GImageToggleButton source, GEvent event) { //_CODE_:redTogButton1:324535:
  toggleUpdate(event, 0);
} //_CODE_:redTogButton1:324535:

public void blueTogButton1_click1(GImageToggleButton source, GEvent event) { //_CODE_:blueTogButton1:267547:
  toggleUpdate(event, 1);
} //_CODE_:blueTogButton1:267547:

public void greenTogButton1_click1(GImageToggleButton source, GEvent event) { //_CODE_:greenTogButton1:260559:
  toggleUpdate(event, 2);
} //_CODE_:greenTogButton1:260559:

public void yellowTogButton1_click1(GImageToggleButton source, GEvent event) { //_CODE_:yellowTogButton1:283661:
  toggleUpdate(event, 3);
} //_CODE_:yellowTogButton1:283661:

public void purpleTogButton1_click1(GImageToggleButton source, GEvent event) { //_CODE_:purpleTogButton1:610276:
  toggleUpdate(event, 4);
} //_CODE_:purpleTogButton1:610276:

public void orangeTogButton1_click1(GImageToggleButton source, GEvent event) { //_CODE_:orangeTogButton1:547732:
  toggleUpdate(event, 5);
} //_CODE_:orangeTogButton1:547732:

public void reddot_click2(GImageButton source, GEvent event) { //_CODE_:reddot:657772:
} //_CODE_:reddot:657772:

public void greendot_click2(GImageButton source, GEvent event) { //_CODE_:greendot:438665:
} //_CODE_:greendot:438665:

public void bluedot_click2(GImageButton source, GEvent event) { //_CODE_:bluedot:934792:
} //_CODE_:bluedot:934792:

public void yellowdot_click2(GImageButton source, GEvent event) { //_CODE_:yellowdot:430374:
} //_CODE_:yellowdot:430374:

public void purpledot_click2(GImageButton source, GEvent event) { //_CODE_:purpledot:404593:
} //_CODE_:purpledot:404593:

public void orangedot_click2(GImageButton source, GEvent event) { //_CODE_:orangedot:893370:
} //_CODE_:orangedot:893370:

public void redon_click2(GImageButton source, GEvent event) { //_CODE_:redon:700357:
} //_CODE_:redon:700357:

public void blueon_click2(GImageButton source, GEvent event) { //_CODE_:blueon:760373:
} //_CODE_:blueon:760373:

public void greenon_click2(GImageButton source, GEvent event) { //_CODE_:greenon:764788:
} //_CODE_:greenon:764788:

public void yellowon_click2(GImageButton source, GEvent event) { //_CODE_:yellowon:429709:
} //_CODE_:yellowon:429709:

public void prupleon_click2(GImageButton source, GEvent event) { //_CODE_:purpleon:798097:
} //_CODE_:purpleon:798097:

public void orangeon_click2(GImageButton source, GEvent event) { //_CODE_:orangeon:464327:
} //_CODE_:orangeon:464327:

public void dropListRed_click1(GDropList source, GEvent event) { //_CODE_:dropListRed:883689:
  getDropdownData(source, event, 0);
} //_CODE_:dropListRed:883689:

public void dropListGreen_click1(GDropList source, GEvent event) { //_CODE_:dropListGreen:214383:
  getDropdownData(source, event, 1);
} //_CODE_:dropListGreen:214383:

public void dropListBlue_click1(GDropList source, GEvent event) { //_CODE_:dropListBlue:850991:
  getDropdownData(source, event, 2);
} //_CODE_:dropListBlue:850991:

public void dropListYellow_click1(GDropList source, GEvent event) { //_CODE_:dropListYellow:637715:
  getDropdownData(source, event, 3);
} //_CODE_:dropListYellow:637715:

public void dropListPurple_click1(GDropList source, GEvent event) { //_CODE_:dropListPurple:621649:
  getDropdownData(source, event, 4);
} //_CODE_:dropListPurple:621649:

public void dropListOrange_click1(GDropList source, GEvent event) { //_CODE_:dropListOrange:901739:
  getDropdownData(source, event, 5);
} //_CODE_:dropListOrange:901739:

public void modeforKnob_clicked1(GOption source, GEvent event) { //_CODE_:modeforKnob:841963:
  println("ampEnv - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:modeforKnob:841963:

public void drawforKnob_clicked1(GOption source, GEvent event) { //_CODE_:drawforKnob:784790:
  println("ampLFO - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:drawforKnob:784790:

public void octave_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:octave_slider1:947832:
  octaveSliderSet(source, event);
} //_CODE_:octave_slider1:947832:

public void envDur_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:envDur_slider1:860031:
  envelopeDuration(source, event);
} //_CODE_:envDur_slider1:860031:

public void showPlayhead_clicked1(GCheckbox source, GEvent event) { //_CODE_:showPlayhead:915718:
  playDisplay(event);
} //_CODE_:showPlayhead:915718:

public void envinPS_clicked1(GCheckbox source, GEvent event) { //_CODE_:envinPS:930059:
  psEnv(event);
} //_CODE_:envinPS:930059:

public void psPitch_clicked1(GCheckbox source, GEvent event) { //_CODE_:psPitch:645877:
  psPitch(event);
} //_CODE_:psPitch:645877:

public void showEnv_clicked1(GCheckbox source, GEvent event) { //_CODE_:showEnv:225755:
  combEnv(event);
} //_CODE_:showEnv:225755:

public void showLFO_clicked1(GCheckbox source, GEvent event) { //_CODE_:showLFO:932922:
  combLFO(event);
} //_CODE_:showLFO:932922:

public void showWav_clicked1(GCheckbox source, GEvent event) { //_CODE_:showWav:832149:
  combWav(event);
} //_CODE_:showWav:832149:

public void expButton1_click2(GImageButton source, GEvent event) { //_CODE_:expButton1:780310:
  println("expButton1 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:expButton1:780310:

public void lfoOnSwitch_clicked1(GCheckbox source, GEvent event) { //_CODE_:lfoOnSwitch:633091:
  lfoOnSwitch(event);
} //_CODE_:lfoOnSwitch:633091:

public void decay_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:decay_slider1:939979:
  sliderUpdate(source, event, 1);
} //_CODE_:decay_slider1:939979:

public void fmTog_clicked1(GOption source, GEvent event) { //_CODE_:fmTog:284432:
  lfoFM(event);
} //_CODE_:fmTog:284432:

public void amTog_clicked1(GOption source, GEvent event) { //_CODE_:amTog:439993:
  lfoAM(event);
} //_CODE_:amTog:439993:

public void exportMp3_click2(GImageButton source, GEvent event) { //_CODE_:exportMp3:578508:
  exportToDisk(event);
} //_CODE_:exportMp3:578508:



// Create all the GUI controls.
// autogenerated do not edit
public void createGUI() {
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.YELLOW_SCHEME);
  G4P.setMouseOverEnabled(false);
  G4P.setDisplayFont("SignPainter", G4P.PLAIN, 19);
  G4P.setInputFont("SignPainter", G4P.BOLD, 30);
  G4P.setSliderFont("Arial", G4P.PLAIN, 6);
  surface.setTitle("SmplASketch");
  backgroundDarkMode = new GImageButton(this, -1, 0, new String[] { "backgroundDarkMode.png", "backgroundDarkMode.png", "backgroundDarkMode.png" } );
  backgroundDarkMode.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  backgroundDarkMode.addEventHandler(this, "imgButton1_click1");
  volknob = new GKnob(this, 996, 475, 100, 100, 0.8f);
  volknob.setTurnRange(110, 70);
  volknob.setTurnMode(GKnob.CTRL_HORIZONTAL);
  volknob.setSensitivity(1);
  volknob.setShowArcOnly(false);
  volknob.setOverArcOnly(false);
  volknob.setIncludeOverBezel(false);
  volknob.setShowTrack(true);
  volknob.setLimits(2.0f, 0.0f, 10.0f);
  volknob.setNbrTicks(11);
  volknob.setStickToTicks(true);
  volknob.setShowTicks(true);
  volknob.setEasing(2.0f);
  volknob.setOpaque(false);
  volknob.addEventHandler(this, "volknob_turn1");
  modeknob = new GKnob(this, 424, 475, 100, 100, 0.8f);
  modeknob.setTurnRange(140, 50);
  modeknob.setTurnMode(GKnob.CTRL_HORIZONTAL);
  modeknob.setSensitivity(1);
  modeknob.setShowArcOnly(false);
  modeknob.setOverArcOnly(false);
  modeknob.setIncludeOverBezel(false);
  modeknob.setShowTrack(true);
  modeknob.setLimits(0.0f, 0.0f, 4.0f);
  modeknob.setNbrTicks(5);
  modeknob.setStickToTicks(true);
  modeknob.setShowTicks(true);
  modeknob.setOpaque(false);
  modeknob.addEventHandler(this, "modeknob_turn1");
  attack_slider = new GCustomSlider(this, 350, 650, 300, 40, "grey_blue");
  attack_slider.setLimits(5.0f, 0.0f, 10.0f);
  attack_slider.setNumberFormat(G4P.DECIMAL, 2);
  attack_slider.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  attack_slider.setOpaque(false);
  attack_slider.addEventHandler(this, "attack_slider_change1");
  sustain_slider = new GCustomSlider(this, 350, 740, 300, 40, "grey_blue");
  sustain_slider.setLimits(5.0f, 0.0f, 10.0f);
  sustain_slider.setNumberFormat(G4P.DECIMAL, 2);
  sustain_slider.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  sustain_slider.setOpaque(false);
  sustain_slider.addEventHandler(this, "sustain_slider_change1");
  release_slider = new GCustomSlider(this, 350, 785, 300, 40, "grey_blue");
  release_slider.setLimits(5.0f, 0.0f, 10.0f);
  release_slider.setNumberFormat(G4P.DECIMAL, 2);
  release_slider.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  release_slider.setOpaque(false);
  release_slider.addEventHandler(this, "release_slider_change1");
  redWavOverlay = new GImageButton(this, 42, 719, 269, 101, new String[] { "wavgray.png", "wavgray.png", "wavgray.png" } );
  redWavOverlay.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  redWavOverlay.addEventHandler(this, "redWavOverlay_click2");
  togGroupwav = new GToggleGroup();
  sinButt = new GOption(this, 25, 720, 90, 45);
  sinButt.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  sinButt.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  sinButt.setOpaque(false);
  sinButt.addEventHandler(this, "sinButt_clicked1");
  triButt = new GOption(this, 123, 720, 90, 45);
  triButt.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  triButt.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  triButt.setOpaque(false);
  triButt.addEventHandler(this, "triButt_clicked1");
  sqrButt = new GOption(this, 25, 774, 90, 45);
  sqrButt.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  sqrButt.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  sqrButt.setOpaque(false);
  sqrButt.addEventHandler(this, "sqrButt_clicked1");
  sawButt = new GOption(this, 123, 774, 90, 45);
  sawButt.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  sawButt.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  sawButt.setOpaque(false);
  sawButt.addEventHandler(this, "sawButt_clicked1");
  stepButt = new GOption(this, 223, 774, 90, 45);
  stepButt.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  stepButt.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  stepButt.setOpaque(false);
  stepButt.addEventHandler(this, "stepButt_clicked1");
  rampButt = new GOption(this, 223, 720, 90, 45);
  rampButt.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  rampButt.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  rampButt.setOpaque(false);
  rampButt.addEventHandler(this, "rampButt_clicked1");
  togGroupwav.addControl(sinButt);
  sinButt.setSelected(true);
  togGroupwav.addControl(triButt);
  togGroupwav.addControl(sqrButt);
  togGroupwav.addControl(sawButt);
  togGroupwav.addControl(stepButt);
  togGroupwav.addControl(rampButt);
  togGroupWavDevControl = new GToggleGroup();
  DevControWav = new GOption(this, 35, 690, 136, 20);
  DevControWav.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  DevControWav.setText(" ");
  DevControWav.setLocalColorScheme(GCScheme.SCHEME_8);
  DevControWav.setOpaque(false);
  DevControWav.addEventHandler(this, "DevControWav_clicked1");
  DefaultWav = new GOption(this, 175, 690, 131, 20);
  DefaultWav.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  DefaultWav.setText(" ");
  DefaultWav.setLocalColorScheme(GCScheme.SCHEME_8);
  DefaultWav.setOpaque(false);
  DefaultWav.addEventHandler(this, "DefaultWav_clicked1");
  togGroupWavDevControl.addControl(DevControWav);
  DevControWav.setSelected(true);
  togGroupWavDevControl.addControl(DefaultWav);
  freq_slider1 = new GCustomSlider(this, 14, 623, 302, 40, "grey_blue");
  freq_slider1.setLimits(0.0f, -20.0f, 20.0f);
  freq_slider1.setNumberFormat(G4P.DECIMAL, 2);
  freq_slider1.setOpaque(false);
  freq_slider1.addEventHandler(this, "freq_slider1_change1");
  bigtone_slider1 = new GCustomSlider(this, 14, 570, 304, 40, "grey_blue");
  bigtone_slider1.setLimits(6, 0, 12);
  bigtone_slider1.setNbrTicks(13);
  bigtone_slider1.setStickToTicks(true);
  bigtone_slider1.setNumberFormat(G4P.INTEGER, 0);
  bigtone_slider1.setOpaque(false);
  bigtone_slider1.addEventHandler(this, "bigtone_slider1_change1");
  lfored = new GImageButton(this, 892, 715, 269, 101, new String[] { "purplelfomenu.png", "purplelfomenu.png", "purplelfomenu.png" } );
  lfored.addEventHandler(this, "lfored_click2");
  lfoGroup1 = new GToggleGroup();
  lfosin = new GOption(this, 873, 716, 92, 45);
  lfosin.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  lfosin.setOpaque(false);
  lfosin.addEventHandler(this, "lfosin_clicked1");
  lfosqr = new GOption(this, 873, 769, 92, 45);
  lfosqr.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  lfosqr.setOpaque(false);
  lfosqr.addEventHandler(this, "lfosqr_clicked1");
  lfotri = new GOption(this, 974, 716, 89, 46);
  lfotri.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  lfotri.setOpaque(false);
  lfotri.addEventHandler(this, "lfotri_clicked1");
  lfosaw = new GOption(this, 974, 770, 89, 44);
  lfosaw.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  lfosaw.setOpaque(false);
  lfosaw.addEventHandler(this, "lfosaw_clicked1");
  lforamp = new GOption(this, 1071, 716, 89, 44);
  lforamp.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  lforamp.setOpaque(false);
  lforamp.addEventHandler(this, "lforamp_clicked1");
  lfostep = new GOption(this, 1071, 770, 90, 45);
  lfostep.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  lfostep.setOpaque(false);
  lfostep.addEventHandler(this, "lfostep_clicked1");
  lfoGroup1.addControl(lfosin);
  lfosin.setSelected(true);
  lfoGroup1.addControl(lfosqr);
  lfoGroup1.addControl(lfotri);
  lfoGroup1.addControl(lfosaw);
  lfoGroup1.addControl(lforamp);
  lfoGroup1.addControl(lfostep);
  lfoControlgGroup1 = new GToggleGroup();
  lfosaveslot = new GOption(this, 888, 687, 127, 20);
  lfosaveslot.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  lfosaveslot.setOpaque(false);
  lfosaveslot.addEventHandler(this, "lfosaveslot_clicked1");
  defaulttheLFO = new GOption(this, 1028, 687, 124, 20);
  defaulttheLFO.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  defaulttheLFO.setOpaque(false);
  defaulttheLFO.addEventHandler(this, "defaulttheLfo_clicked1");
  lfoControlgGroup1.addControl(lfosaveslot);
  lfosaveslot.setSelected(true);
  lfoControlgGroup1.addControl(defaulttheLFO);
  lfoLen_slider1 = new GCustomSlider(this, 690, 660, 160, 40, "grey_blue");
  lfoLen_slider1.setLimits(0.5f, 0.0f, 1.0f);
  lfoLen_slider1.setNumberFormat(G4P.DECIMAL, 2);
  lfoLen_slider1.setOpaque(false);
  lfoLen_slider1.addEventHandler(this, "lfoLen_slider1_change1");
  lowFreq_slider2 = new GCustomSlider(this, 691, 715, 160, 40, "grey_blue");
  lowFreq_slider2.setLimits(0.5f, 0.0f, 1.0f);
  lowFreq_slider2.setNumberFormat(G4P.DECIMAL, 2);
  lowFreq_slider2.setOpaque(false);
  lowFreq_slider2.addEventHandler(this, "lowFreq_slider2_change1");
  highFreq_slider1 = new GCustomSlider(this, 690, 770, 160, 40, "grey_blue");
  highFreq_slider1.setLimits(0.5f, 0.0f, 1.0f);
  highFreq_slider1.setNumberFormat(G4P.DECIMAL, 2);
  highFreq_slider1.setOpaque(false);
  highFreq_slider1.addEventHandler(this, "rangeFreq_slider1_change1");
  calibration = new GCheckbox(this, 1405, 380, 88, 20);
  calibration.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  calibration.setOpaque(false);
  calibration.addEventHandler(this, "calibration_clicked1");
  calibGroup1 = new GToggleGroup();
  showCam = new GOption(this, 1194, 407, 90, 20);
  showCam.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  showCam.setOpaque(false);
  showCam.addEventHandler(this, "showCam_clicked1");
  capturecali = new GOption(this, 1194, 432, 125, 20);
  capturecali.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  capturecali.setOpaque(false);
  capturecali.addEventHandler(this, "capturecali_clicked1");
  calibGroup1.addControl(showCam);
  showCam.setSelected(true);
  calibGroup1.addControl(capturecali);
  showExtract = new GCheckbox(this, 1195, 460, 90, 20);
  showExtract.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  showExtract.setOpaque(false);
  showExtract.addEventHandler(this, "showExtract_clicked1");
  threshold_slider1 = new GCustomSlider(this, 1331, 396, 155, 40, "grey_blue");
  threshold_slider1.setLimits(0.791f, 0.591f, 0.991f);
  threshold_slider1.setNumberFormat(G4P.DECIMAL, 2);
  threshold_slider1.setOpaque(false);
  threshold_slider1.addEventHandler(this, "threshold_slider1_change1");
  zoom_slider2 = new GCustomSlider(this, 1330, 438, 157, 40, "grey_blue");
  zoom_slider2.setLimits(1.0f, 0.8f, 1.2f);
  zoom_slider2.setNumberFormat(G4P.DECIMAL, 2);
  zoom_slider2.setOpaque(false);
  zoom_slider2.addEventHandler(this, "zoom_slider2_change1");
  envClear = new GImageButton(this, 1198, 315, new String[] { "ClearEnvButt.png", "ClearEnvButt.png", "ClearEnvButt.png" } );
  envClear.addEventHandler(this, "envClear_click3");
  FileName = new GLabel(this, 1258, 522, 240, 18);
  FileName.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  FileName.setText("Select File To Analyze");
  FileName.setLocalColorScheme(GCScheme.SCHEME_8);
  FileName.setOpaque(false);
  browseButton = new GImageButton(this, 1190, 520, 64, 22, new String[] { "Browse.png", "Browse.png", "Browse.png" } );
  browseButton.addEventHandler(this, "browseButton_click1");
  smplButton = new GImageButton(this, 792, 8, new String[] { "Smplbutton.png", "Smplbutton.png", "Smplbutton.png" } );
  smplButton.addEventHandler(this, "smplButton1_click2");
  wavClear = new GImageButton(this, 1198, 342, new String[] { "clearwav.png", "clearwav.png", "clearwav.png" } );
  wavClear.addEventHandler(this, "wavClear_click2");
  resetCalib = new GImageButton(this, 1349, 315, new String[] { "Reset Calib.png", "Reset Calib.png", "Reset Calib.png" } );
  resetCalib.addEventHandler(this, "resetCalib_click2");
  clearTheLFO = new GImageButton(this, 1349, 342, new String[] { "clearLFO.png", "clearLFO.png", "clearLFO.png" } );
  clearTheLFO.addEventHandler(this, "clearTheLFO_click2");
  screenColor = new GCustomSlider(this, 1190, 232, 115, 15, "red_yellow18px");
  screenColor.setLimits(1, 0, 3);
  screenColor.setNbrTicks(4);
  screenColor.setStickToTicks(true);
  screenColor.setNumberFormat(G4P.INTEGER, 0);
  screenColor.setOpaque(false);
  screenColor.addEventHandler(this, "ScreenColor_change1");
  lfoColor = new GCustomSlider(this, 1207, 190, 272, 18, "red_yellow18px");
  lfoColor.setLimits(4, 0, 9);
  lfoColor.setNbrTicks(10);
  lfoColor.setStickToTicks(true);
  lfoColor.setShowTicks(true);
  lfoColor.setNumberFormat(G4P.INTEGER, 0);
  lfoColor.setOpaque(false);
  lfoColor.addEventHandler(this, "lfoColor_change1");
  envColor = new GCustomSlider(this, 1207, 149, 272, 18, "red_yellow18px");
  envColor.setLimits(2, 0, 9);
  envColor.setNbrTicks(10);
  envColor.setStickToTicks(true);
  envColor.setShowTicks(true);
  envColor.setNumberFormat(G4P.INTEGER, 0);
  envColor.setOpaque(false);
  envColor.addEventHandler(this, "envColor_change1");
  wavColor = new GCustomSlider(this, 1207, 99, 272, 18, "red_yellow18px");
  wavColor.setLimits(0, 0, 9);
  wavColor.setNbrTicks(10);
  wavColor.setStickToTicks(true);
  wavColor.setShowTicks(true);
  wavColor.setNumberFormat(G4P.INTEGER, 0);
  wavColor.setOpaque(false);
  wavColor.addEventHandler(this, "wavColor_change1");
  thickness = new GCustomSlider(this, 1386, 244, 100, 12, "grey_blue");
  thickness.setLimits(2, 1, 10);
  thickness.setNumberFormat(G4P.INTEGER, 0);
  thickness.setOpaque(false);
  thickness.addEventHandler(this, "thickness_change1");
  browseExport = new GImageButton(this, 1190, 287, 64, 22, new String[] { "Browse.png", "Browse.png", "Browse.png" } );
  browseExport.addEventHandler(this, "browseExport_click2");
  exportLocLabel = new GLabel(this, 1258, 289, 241, 20);
  exportLocLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  exportLocLabel.setText("Select Export Location");
  exportLocLabel.setLocalColorScheme(GCScheme.SCHEME_8);
  exportLocLabel.setOpaque(false);
  fileName = new GTextField(this, 30, 15, 200, 30, G4P.SCROLLBARS_NONE);
  fileName.setPromptText("       SmplName");
  fileName.setLocalColorScheme(GCScheme.RED_SCHEME);
  fileName.setOpaque(true);
  fileName.addEventHandler(this, "fileName_change1");
  saveButt = new GImageButton(this, 260, 11, new String[] { "savebutt.png", "savebutt.png", "savebutt.png" } );
  saveButt.addEventHandler(this, "saveButt_click2");
  backButt = new GImageButton(this, 618, 11, new String[] { "backButt.png", "backButt.png", "backButt.png" } );
  backButt.addEventHandler(this, "backButt_click1");
  playButt = new GImageButton(this, 663, 11, new String[] { "PlayButt.png", "PlayButt.png", "PlayButt.png" } );
  playButt.addEventHandler(this, "playButt_click1");
  stopButt = new GImageButton(this, 705, 11, new String[] { "StopButt.png", "StopButt.png", "StopButt.png" } );
  stopButt.addEventHandler(this, "stopButt_click2");
  forbutt = new GImageButton(this, 748, 11, new String[] { "ForwardButt.png", "ForwardButt.png", "ForwardButt.png" } );
  forbutt.addEventHandler(this, "forButt_click2");
  helpButt = new GImageButton(this, 1470, 17, new String[] { "helpButt.png", "helpButt.png", "helpButt.png" } );
  helpButt.addEventHandler(this, "helpButt_click2");
  preset = new GImageButton(this, 307, 11, new String[] { "openPreset.png", "openPreset.png", "openPreset.png" } );
  preset.addEventHandler(this, "preset_click2");
  photsynthesisImage = new GImageButton(this, 1241, 662, 218, 159, new String[] { "blank.jpg", "blank.jpg", "blank.jpg" } );
  photsynthesisImage.addEventHandler(this, "photsynthesisImage_click2");
  redTogButton1 = new GImageToggleButton(this, 1200, 583);
  redTogButton1.addEventHandler(this, "redTogButton1_click1");
  blueTogButton1 = new GImageToggleButton(this, 1300, 583);
  blueTogButton1.addEventHandler(this, "blueTogButton1_click1");
  greenTogButton1 = new GImageToggleButton(this, 1250, 583);
  greenTogButton1.addEventHandler(this, "greenTogButton1_click1");
  yellowTogButton1 = new GImageToggleButton(this, 1350, 583);
  yellowTogButton1.addEventHandler(this, "yellowTogButton1_click1");
  purpleTogButton1 = new GImageToggleButton(this, 1400, 583);
  purpleTogButton1.addEventHandler(this, "purpleTogButton1_click1");
  orangeTogButton1 = new GImageToggleButton(this, 1450, 583);
  orangeTogButton1.addEventHandler(this, "orangeTogButton1_click1");
  reddot = new GImageButton(this, 1209, 555, new String[] { "red.png", "red.png", "red.png" } );
  reddot.addEventHandler(this, "reddot_click2");
  greendot = new GImageButton(this, 1258, 555, new String[] { "green.png", "green.png", "green.png" } );
  greendot.addEventHandler(this, "greendot_click2");
  bluedot = new GImageButton(this, 1308, 555, new String[] { "blue.png", "blue.png", "blue.png" } );
  bluedot.addEventHandler(this, "bluedot_click2");
  yellowdot = new GImageButton(this, 1358, 555, new String[] { "yellow.png", "yellow.png", "yellow.png" } );
  yellowdot.addEventHandler(this, "yellowdot_click2");
  purpledot = new GImageButton(this, 1408, 555, new String[] { "pruple.png", "pruple.png", "pruple.png" } );
  purpledot.addEventHandler(this, "purpledot_click2");
  orangedot = new GImageButton(this, 1459, 555, new String[] { "orange.png", "orange.png", "orange.png" } );
  orangedot.addEventHandler(this, "orangedot_click2");
  redon = new GImageButton(this, 1209, 555, new String[] { "redPhoto.png", "redPhoto.png", "redPhoto.png" } );
  redon.addEventHandler(this, "redon_click2");
  blueon = new GImageButton(this, 1308, 555, new String[] { "bluePhoto.png", "bluePhoto.png", "bluePhoto.png" } );
  blueon.addEventHandler(this, "blueon_click2");
  greenon = new GImageButton(this, 1258, 555, new String[] { "greenPhoto.png", "greenPhoto.png", "greenPhoto.png" } );
  greenon.addEventHandler(this, "greenon_click2");
  yellowon = new GImageButton(this, 1358, 555, new String[] { "yellowPhoto.png", "yellowPhoto.png", "yellowPhoto.png" } );
  yellowon.addEventHandler(this, "yellowon_click2");
  purpleon = new GImageButton(this, 1408, 555, new String[] { "purplePhoto.png", "purplePhoto.png", "purplePhoto.png" } );
  purpleon.addEventHandler(this, "prupleon_click2");
  orangeon = new GImageButton(this, 1459, 555, new String[] { "orangePhoto.png", "orangePhoto.png", "orangePhoto.png" } );
  orangeon.addEventHandler(this, "orangeon_click2");
  dropListRed = new GDropList(this, 1205, 636, 31, 119, 6, 8);
  dropListRed.setItems(loadStrings("list_883689"), 0);
  dropListRed.setLocalColorScheme(GCScheme.RED_SCHEME);
  dropListRed.addEventHandler(this, "dropListRed_click1");
  dropListGreen = new GDropList(this, 1255, 636, 31, 119, 6, 8);
  dropListGreen.setItems(loadStrings("list_214383"), 1);
  dropListGreen.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  dropListGreen.addEventHandler(this, "dropListGreen_click1");
  dropListBlue = new GDropList(this, 1305, 636, 31, 119, 6, 8);
  dropListBlue.setItems(loadStrings("list_850991"), 2);
  dropListBlue.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  dropListBlue.addEventHandler(this, "dropListBlue_click1");
  dropListYellow = new GDropList(this, 1355, 636, 31, 119, 6, 8);
  dropListYellow.setItems(loadStrings("list_637715"), 3);
  dropListYellow.addEventHandler(this, "dropListYellow_click1");
  dropListPurple = new GDropList(this, 1405, 636, 31, 119, 6, 8);
  dropListPurple.setItems(loadStrings("list_621649"), 4);
  dropListPurple.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  dropListPurple.addEventHandler(this, "dropListPurple_click1");
  dropListOrange = new GDropList(this, 1455, 636, 31, 119, 6, 8);
  dropListOrange.setItems(loadStrings("list_901739"), 5);
  dropListOrange.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  dropListOrange.addEventHandler(this, "dropListOrange_click1");
  modeDisplay = new GLabel(this, 155, 93, 143, 20);
  modeDisplay.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  modeDisplay.setText("Current Mode");
  modeDisplay.setLocalColorScheme(GCScheme.SCHEME_8);
  modeDisplay.setOpaque(false);
  knobGroup1 = new GToggleGroup();
  modeforKnob = new GOption(this, 33, 314, 120, 20);
  modeforKnob.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  modeforKnob.setOpaque(false);
  modeforKnob.addEventHandler(this, "modeforKnob_clicked1");
  drawforKnob = new GOption(this, 195, 314, 120, 20);
  drawforKnob.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  drawforKnob.setOpaque(false);
  drawforKnob.addEventHandler(this, "drawforKnob_clicked1");
  knobGroup1.addControl(modeforKnob);
  modeforKnob.setSelected(true);
  knobGroup1.addControl(drawforKnob);
  pitch = new GLabel(this, 246, 467, 57, 57);
  pitch.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  pitch.setText("C");
  pitch.setOpaque(false);
  octave_slider1 = new GCustomSlider(this, 31, 407, 267, 40, "grey_blue");
  octave_slider1.setLimits(2.0f, 0.0f, 4.0f);
  octave_slider1.setNbrTicks(5);
  octave_slider1.setStickToTicks(true);
  octave_slider1.setNumberFormat(G4P.DECIMAL, 2);
  octave_slider1.setOpaque(false);
  octave_slider1.addEventHandler(this, "octave_slider1_change1");
  envDur_slider1 = new GCustomSlider(this, 31, 355, 267, 40, "grey_blue");
  envDur_slider1.setLimits(1.25f, 0.5f, 2.0f);
  envDur_slider1.setNumberFormat(G4P.DECIMAL, 2);
  envDur_slider1.setOpaque(false);
  envDur_slider1.addEventHandler(this, "envDur_slider1_change1");
  showPlayhead = new GCheckbox(this, 18, 465, 137, 24);
  showPlayhead.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  showPlayhead.setOpaque(false);
  showPlayhead.addEventHandler(this, "showPlayhead_clicked1");
  envinPS = new GCheckbox(this, 18, 489, 212, 23);
  envinPS.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  envinPS.setOpaque(false);
  envinPS.addEventHandler(this, "envinPS_clicked1");
  psPitch = new GCheckbox(this, 18, 512, 213, 22);
  psPitch.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  psPitch.setOpaque(false);
  psPitch.addEventHandler(this, "psPitch_clicked1");
  psPitch.setSelected(true);
  showEnv = new GCheckbox(this, 31, 229, 129, 20);
  showEnv.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  showEnv.setOpaque(false);
  showEnv.addEventHandler(this, "showEnv_clicked1");
  showLFO = new GCheckbox(this, 189, 229, 98, 20);
  showLFO.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  showLFO.setOpaque(false);
  showLFO.addEventHandler(this, "showLFO_clicked1");
  showWav = new GCheckbox(this, 96, 257, 135, 20);
  showWav.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  showWav.setOpaque(false);
  showWav.addEventHandler(this, "showWav_clicked1");
  showWav.setSelected(true);
  wavSlot = new GLabel(this, 62, 155, 80, 20);
  wavSlot.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  wavSlot.setText("Empty");
  wavSlot.setLocalColorScheme(GCScheme.SCHEME_15);
  wavSlot.setOpaque(false);
  LFOSlot = new GLabel(this, 197, 155, 80, 20);
  LFOSlot.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  LFOSlot.setText("Empty");
  LFOSlot.setLocalColorScheme(GCScheme.SCHEME_8);
  LFOSlot.setOpaque(false);
  expButton1 = new GImageButton(this, 1155, 57, new String[] { "expand.png", "expand.png", "expand.png" } );
  expButton1.addEventHandler(this, "expButton1_click2");
  pitchFine = new GLabel(this, 281, 467, 21, 19);
  pitchFine.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  pitchFine.setText(" ");
  pitchFine.setOpaque(false);
  lfoOnSwitch = new GCheckbox(this, 888, 656, 90, 20);
  lfoOnSwitch.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  lfoOnSwitch.setOpaque(false);
  lfoOnSwitch.addEventHandler(this, "lfoOnSwitch_clicked1");
  decay_slider1 = new GCustomSlider(this, 350, 695, 300, 40, "grey_blue");
  decay_slider1.setLimits(5.0f, 0.0f, 10.0f);
  decay_slider1.setNumberFormat(G4P.DECIMAL, 2);
  decay_slider1.setOpaque(false);
  decay_slider1.addEventHandler(this, "decay_slider1_change1");
  fmamlfoGroup1 = new GToggleGroup();
  fmTog = new GOption(this, 1028, 654, 50, 20);
  fmTog.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  fmTog.setOpaque(false);
  fmTog.addEventHandler(this, "fmTog_clicked1");
  amTog = new GOption(this, 1096, 654, 50, 20);
  amTog.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  amTog.setOpaque(false);
  amTog.addEventHandler(this, "amTog_clicked1");
  fmamlfoGroup1.addControl(fmTog);
  fmTog.setSelected(true);
  fmamlfoGroup1.addControl(amTog);
  exportMp3 = new GImageButton(this, 354, 11, new String[] { "Export.png", "Export.png", "Export.png" } );
  exportMp3.addEventHandler(this, "exportMp3_click2");
}

// Variable declarations
// autogenerated do not edit
GImageButton backgroundDarkMode;
GKnob volknob;
GKnob modeknob;
GCustomSlider attack_slider;
GCustomSlider sustain_slider;
GCustomSlider release_slider;
GImageButton redWavOverlay;
GToggleGroup togGroupwav;
GOption sinButt;
GOption triButt;
GOption sqrButt;
GOption sawButt;
GOption stepButt;
GOption rampButt;
GToggleGroup togGroupWavDevControl;
GOption DevControWav;
GOption DefaultWav;
GCustomSlider freq_slider1;
GCustomSlider bigtone_slider1;
GImageButton lfored;
GToggleGroup lfoGroup1;
GOption lfosin;
GOption lfosqr;
GOption lfotri;
GOption lfosaw;
GOption lforamp;
GOption lfostep;
GToggleGroup lfoControlgGroup1;
GOption lfosaveslot;
GOption defaulttheLFO;
GCustomSlider lfoLen_slider1;
GCustomSlider lowFreq_slider2;
GCustomSlider highFreq_slider1;
GCheckbox calibration;
GToggleGroup calibGroup1;
GOption showCam;
GOption capturecali;
GCheckbox showExtract;
GCustomSlider threshold_slider1;
GCustomSlider zoom_slider2;
GImageButton envClear;
GLabel FileName;
GImageButton browseButton;
GImageButton smplButton;
GImageButton wavClear;
GImageButton resetCalib;
GImageButton clearTheLFO;
GCustomSlider screenColor;
GCustomSlider lfoColor;
GCustomSlider envColor;
GCustomSlider wavColor;
GCustomSlider thickness;
GImageButton browseExport;
GLabel exportLocLabel;
GTextField fileName;
GImageButton saveButt;
GImageButton backButt;
GImageButton playButt;
GImageButton stopButt;
GImageButton forbutt;
GImageButton helpButt;
GImageButton preset;
GImageButton photsynthesisImage;
GImageToggleButton redTogButton1;
GImageToggleButton blueTogButton1;
GImageToggleButton greenTogButton1;
GImageToggleButton yellowTogButton1;
GImageToggleButton purpleTogButton1;
GImageToggleButton orangeTogButton1;
GImageButton reddot;
GImageButton greendot;
GImageButton bluedot;
GImageButton yellowdot;
GImageButton purpledot;
GImageButton orangedot;
GImageButton redon;
GImageButton blueon;
GImageButton greenon;
GImageButton yellowon;
GImageButton purpleon;
GImageButton orangeon;
GDropList dropListRed;
GDropList dropListGreen;
GDropList dropListBlue;
GDropList dropListYellow;
GDropList dropListPurple;
GDropList dropListOrange;
GLabel modeDisplay;
GToggleGroup knobGroup1;
GOption modeforKnob;
GOption drawforKnob;
GLabel pitch;
GCustomSlider octave_slider1;
GCustomSlider envDur_slider1;
GCheckbox showPlayhead;
GCheckbox envinPS;
GCheckbox psPitch;
GCheckbox showEnv;
GCheckbox showLFO;
GCheckbox showWav;
GLabel wavSlot;
GLabel LFOSlot;
GImageButton expButton1;
GLabel pitchFine;
GCheckbox lfoOnSwitch;
GCustomSlider decay_slider1;
GToggleGroup fmamlfoGroup1;
GOption fmTog;
GOption amTog;
GImageButton exportMp3;

PImage wavImg;
PImage lfoImg;
PImage modWavImg;
PImage modLFOImg;
PImage modCalibImg;

float threshold = 0.791f;
float shift = 1.0f;

public float[] processImage(PImage img, PImage modImg, Boolean isWav) { //takes the image from the folder changes all red pixels to green and returns float array of drawn wave
  modImg.loadPixels(); //load display pixels
  img.loadPixels(); //load images pizels
  img = crop(img);
  img = threshed(img);
  img.save("newimg.jpg");
  float[] wav = new float[camwidth];

  for (int x = 0; x < camwidth; x++) {
    ArrayList<Integer> readBlackPix = new ArrayList<Integer>(); // create list to hold y values for a single x point
    for (int y = 0; y < camheight; y++) {
      int loc = x + y*camwidth; //calculate pixel location

      // Pull out the 3 color components from pixel
      float r = red(img.pixels[loc]);
      float g = green(img.pixels[loc]);
      float b = blue(img.pixels[loc]);

      // Change red pixels to green to show that it was read
      if (r < 10 && b < 10 && g < 10) {
        r=0;
        b=0;
        g=255;
        readBlackPix.add(y); //add the y value to the list
      }

      // Change displayed pixel to represent coordinates counted
      modImg.pixels[loc] =  color(r, g, b);
    }
    if (readBlackPix.isEmpty()) {
      wav[x]=0;
    } else {
      int avg = findAvgY(readBlackPix);
      float avgFl;
      if (isWav) {
        avgFl = map(avg, camheight, 0, -1, 1);//very confused why it's flipped but that's how the numbers work out
      } else {
        avgFl = map(avg, 0, camheight, 0, 1000);//very confused why it's flipped but that's how the numbers work out
      }
      wav[x] = avgFl;
    }
  }
  modImg.updatePixels();
  return wav;
}

//Grab Proccessed Arrays
public float[] processWavImage() { // feeds in wavImg names to image processing
  return processImage(wavImg, modWavImg, true);
}
public float[] processCalibImage() { // feeds in wavImg names to image processing
  return processImage(camCap, modCalibImg, true);
}
public float[] processLFOImage() { // feeds in wavImg names to image processing
  return processImage(lfoImg, modLFOImg, true);
}

//Modifier Functions
public PImage crop(PImage img) { //crops image from camera to get just the slide
  PImage cropped = img.get((int)(160*shift), (int)(325*shift), camwidth, camheight);
  //cropped.save("cropped.jpg");
  return cropped;
}

public PImage threshed(PImage img) { //crops image from camera to get just the slide
  img.filter(THRESHOLD, threshold);//filters line to black
  //cropped.save("cropped.jpg");
  return img;
}

//Helper functions
public void thresholdMod(GCustomSlider source, GEvent event) {
  if (event == GEvent.RELEASED || event == GEvent.PRESSED || event == GEvent.VALUE_STEADY) {
    threshold = source.getValueF();
  }
}

public void shiftMod(GCustomSlider source, GEvent event) {
  if (event == GEvent.RELEASED || event == GEvent.PRESSED || event == GEvent.VALUE_STEADY) {
    shift = source.getValueF();
  }
}

public int findAvgY(ArrayList<Integer> list) { // find average of y pixels from drawing
  int avg = 0;
  int size = list.size();
  for (int i = 0; i < size; i ++) {
    avg += list.get(i);
  }
  avg = avg/size;
  return avg;
}
Oscil       red;
Oscil       green;
Oscil       blue;
Oscil       yellow;
Oscil       purple;
Oscil       orange;
Wavetable   redtable;
Wavetable   greentable;
Wavetable   bluetable;
Wavetable   yellowtable;
Wavetable   purpletable;
Wavetable   orangetable;

class Photosynthesizer implements Instrument
{

  ADSR adsr;
  // constructor
  Photosynthesizer(float[] Red, float[] Green, float[] Blue, float[] Yellow, float[] Purple, float[] Orange, ADSR env, float hz, int[] indexes, boolean[] switches)
  {
    Summer sum = new Summer();
    adsr = env;
    float[] amp = {1.0f, 0.7f, 0.5f, 0.3f, 0.1f, 0.05f};
    // create oscillators of wavtables from float[]'s
    if(switches[0]) {
    redtable = new Wavetable(Red);
    red  = new Oscil( ((float)indexes[0]+1) * hz, amp[indexes[0]], redtable );
    red.patch( sum );
    }if(switches[1]) {
    greentable = new Wavetable(Green);
    green  = new Oscil( ((float)indexes[1]+1) * hz, amp[indexes[1]], greentable );
    green.patch( sum );
    }if(switches[2]) {
    bluetable = new Wavetable(Blue);
    blue  = new Oscil( ((float)indexes[2]+1) * hz, amp[indexes[2]], bluetable );
    blue.patch( sum );
    }if(switches[3]) {
    yellowtable = new Wavetable(Yellow);
    yellow  = new Oscil( ((float)indexes[3]+1) * hz, amp[indexes[3]], yellowtable );
    yellow.patch( sum );
    }if(switches[4]) {
    purpletable = new Wavetable(Purple);
    purple  = new Oscil( ((float)indexes[4]+1) * hz, amp[indexes[4]], purpletable );
    purple.patch( sum );
    }if(switches[5]) {
    orangetable = new Wavetable(Orange);
    orange  = new Oscil( ((float)indexes[5]+1) * hz, amp[indexes[5]], orangetable );
    orange.patch( sum );
    }
    //Send Wav to ADSR
    sum.patch( adsr );
  }
  //noteOn and noteOred called when out.playNote() is called
  public void noteOn( float dur )
  {
    adsr.noteOn();
    adsr.patch( out );
  }

  public void noteOff()
  {
    adsr.unpatchAfterRelease( out );
    adsr.noteOff();
    noShow = false;
  }
}
//Frequency Variables
String[] note = {"", "F#", "G", "G#", "A", "A#", "B", "C", "C#", "D", "D#", "E", "F", "F#", ""};
float[] noteHz = {Frequency.ofPitch("F#2").asHz(),
  Frequency.ofPitch("F#3").asHz(),
  Frequency.ofPitch("G3").asHz(),
  Frequency.ofPitch("G#3").asHz(),
  Frequency.ofPitch("A3").asHz(),
  Frequency.ofPitch("A#3").asHz(),
  Frequency.ofPitch("B3").asHz(),
  Frequency.ofPitch("C4").asHz(),
  Frequency.ofPitch("C#4").asHz(),
  Frequency.ofPitch("D4").asHz(),
  Frequency.ofPitch("D#4").asHz(),
  Frequency.ofPitch("E4").asHz(),
  Frequency.ofPitch("F4").asHz(),
  Frequency.ofPitch("F#4").asHz(),
  Frequency.ofPitch("G4").asHz()};
float fineAdjust = 0.0f;
float[] oct = {0.25f, 0.5f, 1.0f, 2.0f, 4.0f};
int noteIndex = 7;
int octIndex = 2;
//PS Wav Usage
float[] wavR;
float[] wavG;
float[] wavB;
float[] wavY;
float[] wavP;
float[] wavO;
boolean[] wavSet = {false, false, false, false, false, false};
boolean recordEnabled=false;


//ADSR Generation Code
public float[] mapADSR() {
  float attack;
  float decay;
  float sustain;
  float release;
  if (noSliderTouched) {
    attack = 0.5f;
    decay = 0.5f;
    sustain = 0.5f;
    release = 0.5f;
  } else {
    attack = map(sliderVals[0], 0, 10, 0.f, 1.f);
    decay = map(sliderVals[1], 0, 10, 0.f, 1.f);
    sustain = map(sliderVals[2], 0, 10, 0.f, 1.f);
    release = map(sliderVals[3], 0, 10, 0.f, 1.f);
  }
  return new float[]{attack*envMult, decay*envMult, sustain*envMult, release*envMult};
}

public ADSR genADSR(float maxAmp, float attTime, float decTime, float relTime, float susLvl) {
  return new ADSR( maxAmp, attTime, decTime, susLvl, relTime );
}


//Playback Master Function
public void smpl() {
  if (!showPlayLine) {
    noShow = true;
    linecounter = 700;
  } else {
    linecounter = 0;
  }
  if (mode != 4.0f) {
    float[] wav;
    float[] lfo;
    if (clearWav && wavControl) {
      wav = resetSin;
    } else if (!wavControl) {
      wav = defaultWav;
    } else {
      wav = processWavImage();
    }
    if (clearLFO && lfoControl) {
      lfo = invertFlArr(genSinWav());
    } else if (!lfoControl) {
      lfo = invertFlArr(defaultLFO);
    } else {
      lfo = invertFlArr(processLFOImage());
    }
    float[] envVals = mapADSR();
    ADSR env = genADSR(volume, envVals[0], envVals[1], envVals[3], 0.275f);
    float dur = (envVals[2]*envMult) +(envMult);
    float mappedAdj = map(fineAdjust, -20.0f, 20.0f, noteHz[noteIndex-1]+0.5f-noteHz[noteIndex], noteHz[noteIndex+1]-0.5f-noteHz[noteIndex]);
    float freq = (noteHz[noteIndex]+mappedAdj)*oct[octIndex];
    if (recordEnabled) {
      recorder.beginRecord();
    }
    out.playNote( 0.0f, dur, new SmplInstrument(wav, lfo, env, freq));
    if (recordEnabled) {
      wait(9000);
      recorder.endRecord();
      recorder.save();
    }
  } else {
    photowaveformSmpl();
  }
}

//Playback for Photosynthesis Mode
public void photowaveformSmpl() {
  ArrayList<float[]> processed = processMultiImage(imageMode);
  float photoSampleRate;
  if (photoPitch) {
    photoSampleRate = (noteHz[noteIndex]+fineAdjust)/2;
  } else {
    photoSampleRate = (noteHz[7]+fineAdjust)/2;
  }
  if (photsynthesisDots[0] == true) {
    wavR = processed.get(0);
    wavSet[0] = true;
  } else {
    wavSet[0] = false;
  }
  if (photsynthesisDots[2] == true) {
    wavG = processed.get(1);
    wavSet[1] = true;
  } else {
    wavSet[1] = false;
  }
  if (photsynthesisDots[1] == true) {
    wavB = processed.get(2);
    wavSet[2] = true;
  } else {
    wavSet[2] = false;
  }
  if (photsynthesisDots[3] == true) {
    wavY = processed.get(3);
    wavSet[3] = true;
  } else {
    wavSet[3] = false;
  }
  if (photsynthesisDots[4] == true) {
    wavP = processed.get(4);
    wavSet[4] = true;
  } else {
    wavSet[4] = false;
  }
  if (photsynthesisDots[5] == true) {
    wavO = processed.get(5);
    wavSet[5] = true;
  } else {
    wavSet[5] = false;
  }

  float[] envVals = mapADSR();
  ADSR env = genADSR(volume, envVals[0], envVals[1], envVals[3], 0.275f);
  float dur = (envVals[2]*envMult) +(envMult);
  if (recordEnabled) {
    recorder.beginRecord();
  }
  out.playNote( 0.0f, dur, new Photosynthesizer(wavR, wavG, wavB, wavY, wavP, wavO, env, photoSampleRate, freqArrPhotoMode, wavSet));
  if (recordEnabled) {
    wait(9000);
    recorder.endRecord();
    recorder.save();
  }
}
boolean clearWav = true;
boolean wavControl = true;
boolean lfoControl = true;
boolean clearLFO = true;
boolean clearEnv = true;
boolean susMode = false;
float[] sliderVals = new float[4];
float[] lfoMods = {0.5f, 0.5f, 0.5f};
boolean spaceHit = false;
boolean photoPitch = true;
boolean photoEnvDisplay = false;
boolean lfoOn = false;
boolean noShow = false;
PImage filereset = createImage(camwidth, camheight, RGB);
float[] emptyWav = {0.0f};
boolean fmOn = true;

//UI Setup
public void uiSetup() {
  createGUI();
  bigtone_slider1.setShowTicks(false);
  octave_slider1.setShowTicks(false);
  setAdditionSchemes();
}

//Wav/LFO Generation Functions
public float[] genSinWav() { //create sin wav arr
  float[] sinewave = new float[camwidth];

  for (int i = 0; i < camwidth; i++) {
    sinewave[i] = -sin(TWO_PI*i/camwidth);
  }
  return sinewave;
}

public void defaultSin(boolean wavOrLFO) {
  if (wavOrLFO) {
    defaultWav=resetSin;
  } else {
    defaultLFO=resetSin;
  }
}

public void defaultSqr(boolean wavOrLFO) {
  float[] sqrwav = new float[camwidth];

  for (int i = 0; i < camwidth; i++) {
    if (i < camwidth/2) {
      sqrwav[i] = -1;
    } else {
      sqrwav[i] = 1;
    }
  }
  if (wavOrLFO) {
    defaultWav=sqrwav;
  } else {
    defaultLFO=sqrwav;
  }
}

public void defaultTri(boolean wavOrLFO) {
  float[] triwav = new float[camwidth];
  int counter = 0;
  for (int i = 0; i < camwidth; i++) {
    if (i == 0) {
      counter = 0;
    } else if (i < camwidth/4) {
      counter +=1;
    } else if (i < (camwidth*3)/4) {
      counter -=1;
      triwav[i] = counter;
    } else {
      counter +=1;
    }
    triwav[i] = map(counter, -((camwidth/4)-1), ((camwidth/4)-1), 1, -1);
  }
  if (wavOrLFO) {
    defaultWav=triwav;
  } else {
    defaultLFO=triwav;
  }
}

public void defaultSaw(boolean wavOrLFO) {
  float[] sawwav = new float[camwidth];
  int counter = camwidth/2;
  for (int i = 0; i < camwidth; i++) {
    counter -=1;
    sawwav[i] = map(counter, -((camwidth/2)-1), ((camwidth/2)-1), 1, -1);
  }
  if (wavOrLFO) {
    defaultWav=sawwav;
  } else {
    defaultLFO=sawwav;
  }
}

public void defaultRamp(boolean wavOrLFO) {
  float[] rampwav = new float[camwidth];
  int counter = -(camwidth/2);
  for (int i = 0; i < camwidth; i++) {
    counter +=1;
    rampwav[i] = map(counter, -((camwidth/2)-1), ((camwidth/2)-1), 1, -1);
  }
  if (wavOrLFO) {
    defaultWav=rampwav;
  } else {
    defaultLFO=rampwav;
  }
}

public void defaultStep(boolean wavOrLFO) {
  float[] stepwav = new float[camwidth];
  int counter = 0;
  int step = 0;
  for (int i = 0; i < camwidth; i++) {
    if (step != camwidth/40) {
      step++;
    } else {
      counter++;
      step=0;
    }
    stepwav[i] = map(counter, 0, (camwidth/16)-1, 1, -1);
  }
  if (wavOrLFO) {
    defaultWav=stepwav;
  } else {
    defaultLFO=stepwav;
  }
}
PImage imageMode;
int[] freqArrPhotoMode = {0, 1, 2, 3, 4, 5};
boolean[] photsynthesisDots = {false, false, false, false, false, false};

public ArrayList<float[]> processMultiImage(PImage img) {//Image processing function for multi color extraction
  img.loadPixels(); //load images pizels
  int imgWidth = img.width;
  int imgHeight = img.height;

  float[] redWav = new float[imgWidth];
  float[] greenWav = new float[imgWidth];
  float[] blueWav = new float[imgWidth];
  float[] yellowWav = new float[imgWidth];
  float[] purpleWav = new float[imgWidth];
  float[] orangeWav = new float[imgWidth];


  for (int x = 0; x < imgWidth; x++) {
    Integer redPix = 0;
    Integer greenPix = 0;
    Integer bluePix = 0;
    Integer yellowPix = 0;
    Integer purplePix = 0;
    Integer orangePix = 0;

    for (int y = 0; y < imgHeight; y++) {
      int loc = x + y*imgWidth; //calculate pixel location

      // Pull out the 3 color components from pixel
      float r = red(img.pixels[loc]);
      float g = green(img.pixels[loc]);
      float b = blue(img.pixels[loc]);

      if (b < 100 && r > 200 && g > 90 && g < 200) {
        orangePix++;
      } else if (b < 220 && r > 200 && g > 200) {
        yellowPix++;
      } else if (b > 150 && r > 150 && g < 90) {
        purplePix++;
      } else if (b > r && b > g) {
        bluePix++;
      } else if (r > b && r > g) {
        redPix++;
      } else if (g > b && g > r) {
        greenPix++;
      }
    }
    redWav[x] = map(redPix, 0, imgHeight, 1, -1);
    greenWav[x] = map(greenPix, 0, imgHeight, 1, -1);
    blueWav[x] = map(bluePix, 0, imgHeight, 1, -1);
    yellowWav[x] = map(yellowPix, 0, imgHeight, 1, -1);
    purpleWav[x] = map(purplePix, 0, imgHeight, 1, -1);
    orangeWav[x] = map(orangePix, 0, imgHeight, 1, -1);
  }
  ArrayList<float[]> returnThis = new ArrayList<float[]>();
  returnThis.add(redWav);
  returnThis.add(greenWav);
  returnThis.add(blueWav);
  returnThis.add(yellowWav);
  returnThis.add(purpleWav);
  returnThis.add(orangeWav);

  return returnThis;
}
float volume = 0.2f;
float wavMult = 1;
float envMult = 1;
float lfoMult = 1;
float lfoBound = 0.5f;
float lfoRange = 1.5f;

public void resetWav() {
  wavMult= 1;
  clearWav = true;
  filereset.save("wav_image.jpg");
  wavSlot.setText("Empty");
  octave_slider1.setLimits(2.0f, 0.0f, 4.0f);
  pitch.setText("C");
  pitchFine.setText("");
  noteIndex = 7;
  octIndex = 2;
  freq_slider1.setLimits(0.0f, -20.0f, 20.0f);
  bigtone_slider1.setLimits(6, 0, 12);
  DevControWav.setSelected(true);
  wavControl=true;
  defaultWav = resetSin;
  sinButt.setSelected(true);
}

public void resetLFO() {
  lfoMult = 1;
  clearLFO = true;
  lfoControl=true;
  defaultLFO = resetSin;
  lfoLen_slider1.setLimits(0.5f, 0.0f, 1.0f);
  lowFreq_slider2.setLimits(0.5f, 0.0f, 1.0f);
  highFreq_slider1.setLimits(0.5f, 0.0f, 1.0f);
  lfoOnSwitch.setSelected(false);
  lfoOn = false;
  lfosin.setSelected(true);
  lfosaveslot.setSelected(true);
  fmTog.setSelected(true);
  lfoMods = new float[] {0.5f, 0.5f, 0.5f};
  filereset.save("lfo_image.jpg");
  LFOSlot.setText("Empty");
  fmOn = true;
}

public void resetEnv() {
  attack_slider.setLimits(5.0005f, 0.01f, 10);
  decay_slider1.setLimits(5.005f, 0.01f, 10);
  sustain_slider.setLimits(5.005f, 0.01f, 10);
  release_slider.setLimits(5.005f, 0.01f, 10);
  sliderVals = new float[]{5, 5, 5, 5};
  clearEnv = true;
  envMult = 1;
  envDur_slider1.setLimits(1.25f, 0.5f, 2.0f);
}

public void resetCalib() {
  zoom_slider2.setLimits(1.0f, 0.8f, 1.2f);
  threshold_slider1.setLimits(0.791f, 0.591f, 0.991f);
  threshold = 0.791f;
  shift = 1.0f;
}

public void clearCache() {
  resetWav();
  resetLFO();
  resetEnv();
  println("Image Cache Cleared");
}

public void wait(int time) {
  int start = millis();
  while (millis() <= start+time) {
  }
}

public float[] invertFlArr(float[] arr) {
  float[] arrCopy = new float[arr.length];
  for (int i = 0; i < arr.length; i ++) {
    arrCopy[i]= -arr[i];
  }
  return arrCopy;
}
Oscil       wave;
Oscil       lfo;
Wavetable   wavtable;
Wavetable   lfotable;
Constant lfoAdd;
class SmplInstrument implements Instrument
{

  ADSR adsr;
  // constructor
  SmplInstrument(float[] wavCapture, float[] lfoCapture, ADSR env, float hz)
  {
    adsr = env;
    // create oscillators of wavtable from float[]
    wavtable = new Wavetable(wavCapture);
    wave  = new Oscil( hz, 0.5f, wavtable );

    if (lfoOn) {
      if(fmOn){
      lfotable = new Wavetable(lfoCapture);
      float freq = map(lfoMods[0], 0.0f, 1.0f, 0.05f, 5.0f);
      float amp = map(lfoMods[2], 0.0f, 1.0f, 000.0f, 400.0f);
      lfoAdd = new Constant(map(lfoMods[1], 0.0f, 1.0f, 300.0f, 400.0f));
      Summer lfoSum = new Summer();
      lfo  = new Oscil(freq, amp, lfotable );
      lfoAdd.patch(lfoSum);
      lfo.patch(lfoSum);
      //send LFO to to Wav
      lfoSum.patch( wave.frequency );
      } else {
      lfotable = new Wavetable(lfoCapture);
      float freq = map(lfoMods[0], 0.0f, 1.0f, 0.05f, 5.0f);
      float amp = lfoMods[2];
      lfo  = new Oscil(freq, amp, lfotable );
      lfo.patch(wave.amplitude);
      }
    }
    //Send Wav to ADSR
    wave.patch( adsr );
  }
  //noteOn and noteOff called when out.playNote() is called
  public void noteOn( float dur )
  {
    adsr.noteOn();
    adsr.patch( out );
  }

  public void noteOff()
  {
    adsr.unpatchAfterRelease( out );
    adsr.noteOff();
    noShow = false;
  }
}
float[] defaultWav = resetSin;
float[] defaultLFO = resetSin;
boolean noSliderTouched = true;
String trueFileName = "Untitled";

//Main Window
public void setModeKnob(GKnob source) {
  mode = source.getValueF();
}

public void setVolKnob(GKnob source) {
  volume = Math.round(source.getValueI()) * 0.1f;//Round volume
}

public void helpLink(GEvent event) {
  if (event == GEvent.CLICKED) {
    helpButton();
  }
}

public void smplUIButton(GEvent event) {
  if (event == GEvent.CLICKED) {
    smpl();
  }
}

public void centerFileName(GTextField source, GEvent event) {
  if (event == GEvent.ENTERED) {
    //int len = 20;
    String text = source.getText();
    //String newText = "";
    //int space = (int)(len - text.length())/2;
    //for (int i = 0; i < space; i ++) {
    //  newText += " ";
    //}
    trueFileName = text;
    //source.insertText(newText, 0);
  }
}

public void exportToDisk(GEvent event) {
  if (event == GEvent.CLICKED) {
    recordEnabled=true;
    if (saveLoc != "") {
      recorder = minim.createRecorder(out, saveLoc+"/"+trueFileName+".wav");
    } else {
      if (fileName.getText() != "") {
        recorder = minim.createRecorder(out, trueFileName+".wav");
      } else {
        recorder = minim.createRecorder(out, "untitled.wav");
      }
    }

    smpl();
    recordEnabled=false;
  }
}

//Main Controls
public void playDisplay(GEvent event) {
  if (event == GEvent.SELECTED) {
    showPlayLine = true;
  } else {
    showPlayLine = false;
  }
}

public void psEnv(GEvent event) {
  if (event == GEvent.SELECTED) {
    photoEnvDisplay = true;
  } else {
    photoEnvDisplay = false;
  }
}

public void psPitch(GEvent event) {
  if (event == GEvent.SELECTED) {
    photoPitch = true;
  } else {
    photoPitch = false;
  }
}

public void envelopeDuration(GCustomSlider source, GEvent event) {
  if (event == GEvent.RELEASED) {
    envMult = source.getValueF();
  }
}

public void octaveSliderSet(GCustomSlider source, GEvent event) {
  if (event == GEvent.RELEASED) {
    octIndex = source.getValueI();
  }
}

//Wav Device Control
public void  wavDeviceOn(GEvent event) {
  if (event == GEvent.SELECTED) {
    wavControl = true;
  }
}

public void  wavDeviceOff(GEvent event) {
  if (event == GEvent.SELECTED) {
    wavControl = false;
  }
}

// Wav Selection
public void sinWavSelect(GEvent event) {
  if (event == GEvent.SELECTED) {
    defaultSin(true);
  }
}
public void triWavSelect(GEvent event) {
  if (event == GEvent.SELECTED) {
    defaultTri(true);
  }
}
public void sqrWavSelect(GEvent event) {
  if (event == GEvent.SELECTED) {
    defaultSqr(true);
  }
}
public void sawWavSelect(GEvent event) {
  if (event == GEvent.SELECTED) {
    defaultSaw(true);
  }
}
public void stepWavSelect(GEvent event) {
  if (event == GEvent.SELECTED) {
    defaultStep(true);
  }
}
public void rampWavSelect(GEvent event) {
  if (event == GEvent.SELECTED) {
    defaultRamp(true);
  }
}

//Wave Slider Extraction
public void pitchFineAdjust(GCustomSlider source, GEvent event) {
  if (event == GEvent.RELEASED) {
    fineAdjust = source.getValueF();
    if (fineAdjust == 0) {
      pitchFine.setText("");
    } else if (fineAdjust > 0) {
      pitchFine.setText("+");
    } else {
      pitchFine.setText("-");
    }
  }
}

public void pitchCoarseAdjust(GCustomSlider source, GEvent event) {
  if (event == GEvent.RELEASED) {
    noteIndex = source.getValueI()+1;
    pitch.setText(note[noteIndex]);
  }
}

//LFO Controls
public void lfoOnSwitch(GEvent event) {
  if (event == GEvent.SELECTED) {
    lfoOn = true;
  } else {
    lfoOn = false;
  }
}

//LFO Device Control
public void  lfoDeviceOn(GEvent event) {
  if (event == GEvent.SELECTED) {
    lfoControl = true;
  }
}

public void  lfoDeviceOff(GEvent event) {
  if (event == GEvent.SELECTED) {
    lfoControl = false;
  }
}

//LFO Selection
public void sinLFOSelect(GEvent event) {
  if (event == GEvent.SELECTED) {
    defaultSin(false);
  }
}
public void triLFOSelect(GEvent event) {
  if (event == GEvent.SELECTED) {
    defaultTri(false);
  }
}
public void sqrLFOSelect(GEvent event) {
  if (event == GEvent.SELECTED) {
    defaultSqr(false);
  }
}
public void sawLFOSelect(GEvent event) {
  if (event == GEvent.SELECTED) {
    defaultSaw(false);
  }
}
public void stepLFOSelect(GEvent event) {
  if (event == GEvent.SELECTED) {
    defaultStep(false);
  }
}
public void rampLFOSelect(GEvent event) {
  if (event == GEvent.SELECTED) {
    defaultRamp(false);
  }
}

//LFO Slider Extraction
public void sliderUpdateLFO(GCustomSlider source, GEvent event, int index) {
  if (event == GEvent.RELEASED) {
    lfoMods[index] = source.getValueF();
  }
}

public void lfoFM(GEvent event) {
  if (event == GEvent.SELECTED) fmOn = true;
}
public void lfoAM(GEvent event) {
  if (event == GEvent.SELECTED) fmOn = false;
}


//Envelope Slider Extraction
public void sliderUpdate(GCustomSlider source, GEvent event, int index) {
  noSliderTouched = false;
  if (event == GEvent.RELEASED) {
    sliderVals[index] = source.getValueF();
  }
}

//Combined playback controls
public void combEnv(GEvent event) {
  if (event == GEvent.SELECTED) {
    drawCombEnv=true;
  } else {
    drawCombEnv=false;
  }
}

public void combLFO(GEvent event) {
  if (event == GEvent.SELECTED) {
    drawCombLFO=true;
  } else {
    drawCombLFO=false;
  }
}

public void combWav(GEvent event) {
  if (event == GEvent.SELECTED) {
    drawCombWav=true;
  } else {
    drawCombWav=false;
  }
}

//Photosynthesis Info Extraction
public void getDropdownData(GDropList source, GEvent event, int index) {
  if (event == GEvent.SELECTED) {
    freqArrPhotoMode[index] = source.getSelectedIndex();
  }
}

public void toggleUpdate(GEvent event, int index) {
  if (event == GEvent.CLICKED) {
    photsynthesisDots[index] = !photsynthesisDots[index];
  }
}

public void psSearchFile(GEvent event) {
  if (event == GEvent.CLICKED) {
    selectPhotosynthesisFile();
  }
}

//Calibration Control
public void calibrationOn(GEvent event) {
  if (event == GEvent.SELECTED) {
    calibMode = true;
  }
  if (event == GEvent.DESELECTED) {
    calibMode = false;
    filereset.save("calib.jpg");
  }
}

public void calibCam(GEvent event) {
  if (event == GEvent.SELECTED) {
    camVsCapCalib = true;
  }
}

public void calibCapture(GEvent event) {
  if (event == GEvent.SELECTED) {
    camVsCapCalib = false;
  }
}

public void calibExtract(GEvent event) {
  if (event == GEvent.SELECTED) {
    extraction = true;
  } else if (event == GEvent.DESELECTED) {
    extraction = false;
  }
}

//Color Controls
public void strokeSet(GCustomSlider source, GEvent event) {
  if (event == GEvent.RELEASED || event == GEvent.PRESSED || event == GEvent.VALUE_STEADY) {
    thickStroke = source.getValueI();
  }
}

public void colorControl(GCustomSlider source, GEvent event, int index) {
  if (event == GEvent.RELEASED) {
    int colorDraw = source.getValueI();
    if (colorDraw == 0) {
      setColor(index, 255, 0, 0); //red
    } else if (colorDraw == 1) {
      setColor(index, 0, 255, 0); //green
    } else if (colorDraw == 2) {
      setColor(index, 0, 0, 255); //blue
    } else if (colorDraw == 3) {
      setColor(index, 255, 0, 255); //pink
    } else if (colorDraw == 4) {
      setColor(index, 102, 45, 145); //purple
    } else if (colorDraw == 5) {
      setColor(index, 255, 255, 0); //yellow
    } else if (colorDraw == 6) {
      setColor(index, 241, 90, 36); //orange
    } else if (colorDraw == 7) {
      setColor(index, 96, 56, 19); //brown
    } else if (colorDraw == 8) {
      setColor(index, 0, 0, 0); //black
    } else if (colorDraw == 9) {
      setColor(index, 255, 255, 255); //white
    }
  }
}

public void screenColorControl(GCustomSlider source, GEvent event) {
  if (event == GEvent.RELEASED) {
    int colorDraw = source.getValueI();
    if (colorDraw == 0) {
      screenColorNum = 255; //white
    } else if (colorDraw == 1) {
      screenColorNum = 200; //light grey
    } else if (colorDraw == 2) {
      screenColorNum = 102; //dark grey
    } else if (colorDraw == 3) {
      screenColorNum = 0; //black
    }
  }
}

//Reset Controls
public void setExport(GEvent event) {
  if (event == GEvent.CLICKED) {
    selectSaveLoc();
  }
}

public void envRButton(GEvent event) {
  if (event == GEvent.CLICKED) {
    resetEnv();
  }
}
public void wavRButton(GEvent event) {
  if (event == GEvent.CLICKED) {
    resetWav();
  }
}
public void calibRButton(GEvent event) {
  if (event == GEvent.CLICKED) {
    resetCalib();
  }
}
public void lfoRButton(GEvent event) {
  if (event == GEvent.CLICKED) {
    resetLFO();
  }
}


  public void settings() { size(1512, 850, JAVA2D);
smooth(10); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "smplASketchMinim" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
