/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:backgroundDarkMode:814029:
  println("imgButton1 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:backgroundDarkMode:814029:

public void volknob_turn1(GKnob source, GEvent event) { //_CODE_:volknob:531573:
  println("knob1 - GKnob >> GEvent." + event + " @ " + millis());
} //_CODE_:volknob:531573:

public void modeknob_turn1(GKnob source, GEvent event) { //_CODE_:modeknob:804666:
  println("knob2 - GKnob >> GEvent." + event + " @ " + millis());
} //_CODE_:modeknob:804666:

public void attack_slider_change1(GCustomSlider source, GEvent event) { //_CODE_:attack_slider:517428:
  println("custom_slider1 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:attack_slider:517428:

public void sustain_slider_change1(GCustomSlider source, GEvent event) { //_CODE_:sustain_slider:446330:
  println("custom_slider2 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:sustain_slider:446330:

public void release_slider_change1(GCustomSlider source, GEvent event) { //_CODE_:release_slider:235931:
  println("custom_slider3 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:release_slider:235931:

public void redWavOverlay_click2(GImageButton source, GEvent event) { //_CODE_:redWavOverlay:451286:
  println("redWavOverlay - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:redWavOverlay:451286:

public void sinButt_clicked1(GOption source, GEvent event) { //_CODE_:sinButt:511167:
  println("sinButt - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:sinButt:511167:

public void triButt_clicked1(GOption source, GEvent event) { //_CODE_:triButt:532566:
  println("triButt - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:triButt:532566:

public void sqrButt_clicked1(GOption source, GEvent event) { //_CODE_:sqrButt:650107:
  println("sqrButt - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:sqrButt:650107:

public void sawButt_clicked1(GOption source, GEvent event) { //_CODE_:sawButt:584368:
  println("sawButt - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:sawButt:584368:

public void stepButt_clicked1(GOption source, GEvent event) { //_CODE_:stepButt:289370:
  println("stepButt - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:stepButt:289370:

public void rampButt_clicked1(GOption source, GEvent event) { //_CODE_:rampButt:866973:
  println("rampButt - GOption >> GEvent." + event + " @ " + millis());
} //_CODE_:rampButt:866973:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.YELLOW_SCHEME);
  G4P.setMouseOverEnabled(false);
  G4P.setDisplayFont("SignPainter", G4P.BOLD, 20);
  surface.setTitle("SmplASketch");
  backgroundDarkMode = new GImageButton(this, -1, 0, new String[] { "backgroundDarkMode.png", "backgroundDarkMode.png", "backgroundDarkMode.png" } );
  backgroundDarkMode.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  backgroundDarkMode.addEventHandler(this, "imgButton1_click1");
  volknob = new GKnob(this, 996, 475, 100, 100, 0.8);
  volknob.setTurnRange(110, 70);
  volknob.setTurnMode(GKnob.CTRL_HORIZONTAL);
  volknob.setSensitivity(1);
  volknob.setShowArcOnly(false);
  volknob.setOverArcOnly(false);
  volknob.setIncludeOverBezel(false);
  volknob.setShowTrack(true);
  volknob.setLimits(0.2, 0.0, 1.0);
  volknob.setNbrTicks(11);
  volknob.setStickToTicks(true);
  volknob.setShowTicks(true);
  volknob.setEasing(2.0);
  volknob.setOpaque(false);
  volknob.addEventHandler(this, "volknob_turn1");
  modeknob = new GKnob(this, 424, 475, 100, 100, 0.8);
  modeknob.setTurnRange(140, 50);
  modeknob.setTurnMode(GKnob.CTRL_HORIZONTAL);
  modeknob.setSensitivity(1);
  modeknob.setShowArcOnly(false);
  modeknob.setOverArcOnly(false);
  modeknob.setIncludeOverBezel(false);
  modeknob.setShowTrack(true);
  modeknob.setLimits(0.0, 0.0, 4.0);
  modeknob.setNbrTicks(5);
  modeknob.setStickToTicks(true);
  modeknob.setShowTicks(true);
  modeknob.setOpaque(false);
  modeknob.addEventHandler(this, "modeknob_turn1");
  attack_slider = new GCustomSlider(this, 350, 660, 300, 40, "grey_blue");
  attack_slider.setLimits(0.5, 0.0, 1.0);
  attack_slider.setNumberFormat(G4P.DECIMAL, 2);
  attack_slider.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  attack_slider.setOpaque(false);
  attack_slider.addEventHandler(this, "attack_slider_change1");
  sustain_slider = new GCustomSlider(this, 350, 715, 300, 40, "grey_blue");
  sustain_slider.setLimits(0.5, 0.0, 1.0);
  sustain_slider.setNumberFormat(G4P.DECIMAL, 2);
  sustain_slider.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  sustain_slider.setOpaque(false);
  sustain_slider.addEventHandler(this, "sustain_slider_change1");
  release_slider = new GCustomSlider(this, 350, 770, 300, 40, "grey_blue");
  release_slider.setLimits(0.5, 0.0, 1.0);
  release_slider.setNumberFormat(G4P.DECIMAL, 2);
  release_slider.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  release_slider.setOpaque(false);
  release_slider.addEventHandler(this, "release_slider_change1");
  redWavOverlay = new GImageButton(this, 42, 719, 269, 101, new String[] { "redstuff.png", "redstuff.png", "redstuff.png" } );
  redWavOverlay.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  redWavOverlay.addEventHandler(this, "redWavOverlay_click2");
  togGroupwav = new GToggleGroup();
  sinButt = new GOption(this, 25, 720, 90, 45);
  sinButt.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  sinButt.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  sinButt.setOpaque(false);
  sinButt.addEventHandler(this, "sinButt_clicked1");
  triButt = new GOption(this, 123, 720, 90, 45);
  triButt.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  triButt.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  triButt.setOpaque(false);
  triButt.addEventHandler(this, "triButt_clicked1");
  sqrButt = new GOption(this, 25, 774, 90, 45);
  sqrButt.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  sqrButt.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  sqrButt.setOpaque(false);
  sqrButt.addEventHandler(this, "sqrButt_clicked1");
  sawButt = new GOption(this, 123, 774, 90, 45);
  sawButt.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  sawButt.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  sawButt.setOpaque(false);
  sawButt.addEventHandler(this, "sawButt_clicked1");
  stepButt = new GOption(this, 223, 774, 90, 45);
  stepButt.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  stepButt.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  stepButt.setOpaque(false);
  stepButt.addEventHandler(this, "stepButt_clicked1");
  rampButt = new GOption(this, 223, 720, 90, 45);
  rampButt.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  rampButt.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  rampButt.setOpaque(false);
  rampButt.addEventHandler(this, "rampButt_clicked1");
  togGroupwav.addControl(sinButt);
  sinButt.setSelected(true);
  togGroupwav.addControl(triButt);
  togGroupwav.addControl(sqrButt);
  togGroupwav.addControl(sawButt);
  togGroupwav.addControl(stepButt);
  togGroupwav.addControl(rampButt);
}

// Variable declarations 
// autogenerated do not edit
GImageButton backgroundDarkMode; 
GKnob volknob; 
GKnob modeknob; 
GCustomSlider attack_slider; 
GCustomSlider sustain_slider; 
GCustomSlider release_slider; 
GImageButton redWavOverlay; 
GToggleGroup togGroupwav; 
GOption sinButt; 
GOption triButt; 
GOption sqrButt; 
GOption sawButt; 
GOption stepButt; 
GOption rampButt; 
